// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.7
// Generated by Style Dictionary v5.1.4
//
// Context: Component: MediaPlayer
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial MediaPlayer Design Tokens
///
/// Usage:
///   AdvertorialMediaPlayerTokens.Colors.light.primaryBgIdle
///   AdvertorialMediaPlayerTokens.Sizing.compact.height
///   AdvertorialMediaPlayerTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialMediaPlayerTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialMediaPlayerSizingTokens: Sendable {
        var podcastPlayButtonSize: CGFloat { get }
        var vidPlayerBottomBarGapSpace: CGFloat { get }
        var audioPlayerHeaderStackSpace: CGFloat { get }
        var videoTimeBadgeFontFamily: String { get }
        var vidPlayerControlButtonSize: CGFloat { get }
        var vidPlayerControlButtonIconSizeHover: CGFloat { get }
        var vidPlayerTimecodeFontSize: CGFloat { get }
        var vidPlayerTimecodeContainerMinWidthSize: CGFloat { get }
        var vidPlayerProgressBarContainerHeightSize: CGFloat { get }
        var vidPlayerUnmuteButtonWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialMediaPlayerSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialMediaPlayerSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let podcastPlayButtonSize: CGFloat = 48
            public let vidPlayerBottomBarGapSpace: CGFloat = 0
            public let audioPlayerHeaderStackSpace: CGFloat = 56
            public let videoTimeBadgeFontFamily: String = "Lucida Grande"
            public let vidPlayerControlButtonSize: CGFloat = 42
            public let vidPlayerControlButtonIconSizeHover: CGFloat = 28
            public let vidPlayerTimecodeFontSize: CGFloat = 14
            public let vidPlayerTimecodeContainerMinWidthSize: CGFloat = 45
            public let vidPlayerProgressBarContainerHeightSize: CGFloat = 24
            public let vidPlayerUnmuteButtonWidthSize: CGFloat = 220
        }

        public struct Regular: AdvertorialMediaPlayerSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let podcastPlayButtonSize: CGFloat = 48
            public let vidPlayerBottomBarGapSpace: CGFloat = 16
            public let audioPlayerHeaderStackSpace: CGFloat = 56
            public let videoTimeBadgeFontFamily: String = "Lucida Grande"
            public let vidPlayerControlButtonSize: CGFloat = 42
            public let vidPlayerControlButtonIconSizeHover: CGFloat = 28
            public let vidPlayerTimecodeFontSize: CGFloat = 18
            public let vidPlayerTimecodeContainerMinWidthSize: CGFloat = 58
            public let vidPlayerProgressBarContainerHeightSize: CGFloat = 42
            public let vidPlayerUnmuteButtonWidthSize: CGFloat = 220
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialMediaPlayerTypographyTokens: Sendable {
        var podcastPlayerLabel: TextStyle { get }
        var videoAdTime: TextStyle { get }
        var videoPlayerTime: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialMediaPlayerTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialMediaPlayerTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let podcastPlayerLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let videoAdTime: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoPlayerTime: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }

        public struct Regular: AdvertorialMediaPlayerTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let podcastPlayerLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let videoAdTime: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoPlayerTime: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }
    }
}
