// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: BreakingNews
Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Advertorial BreakingNews Design Tokens
///
/// Usage:
///   AdvertorialBreakingNewsTokens.Colors.light.primaryBgIdle
///   AdvertorialBreakingNewsTokens.Sizing.compact.height
///   AdvertorialBreakingNewsTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialBreakingNewsTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialBreakingNewsSizingTokens: Sendable {
        var breakingNewsContainerHeightSize: CGFloat { get }
        var breakingNewsBadgeUpperTitleFontSize: CGFloat { get }
        var breakingNewsBadgeLowerTitleFontSize: CGFloat { get }
        var breakingNewsBadgeUpperTitleLineHeight: CGFloat { get }
        var breakingNewsBadgeLowerTitleLineHeight: CGFloat { get }
        var breakingNewsBadgeTitelsStackSpace: CGFloat { get }
        var breakingNewsScrollingTextFontSize: CGFloat { get }
        var breakingNewsScrollingTextLineHeight: CGFloat { get }
        var breakingNewsBadgeInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialBreakingNewsSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialBreakingNewsSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let breakingNewsContainerHeightSize: CGFloat = 56
            public let breakingNewsBadgeUpperTitleFontSize: CGFloat = 13
            public let breakingNewsBadgeLowerTitleFontSize: CGFloat = 23
            public let breakingNewsBadgeUpperTitleLineHeight: CGFloat = 13
            public let breakingNewsBadgeLowerTitleLineHeight: CGFloat = 21
            public let breakingNewsBadgeTitelsStackSpace: CGFloat = 0
            public let breakingNewsScrollingTextFontSize: CGFloat = 21
            public let breakingNewsScrollingTextLineHeight: CGFloat = 24
            public let breakingNewsBadgeInlineSpace: CGFloat = 6
        }

        public struct Regular: AdvertorialBreakingNewsSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let breakingNewsContainerHeightSize: CGFloat = 56
            public let breakingNewsBadgeUpperTitleFontSize: CGFloat = 17
            public let breakingNewsBadgeLowerTitleFontSize: CGFloat = 30
            public let breakingNewsBadgeUpperTitleLineHeight: CGFloat = 12
            public let breakingNewsBadgeLowerTitleLineHeight: CGFloat = 21
            public let breakingNewsBadgeTitelsStackSpace: CGFloat = 4
            public let breakingNewsScrollingTextFontSize: CGFloat = 21
            public let breakingNewsScrollingTextLineHeight: CGFloat = 24
            public let breakingNewsBadgeInlineSpace: CGFloat = 26
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialBreakingNewsTypographyTokens: Sendable {
        var breakingNewsText: TextStyle { get }
        var breakingNewsUpperTitle: TextStyle { get }
        var breakingNewsLowerTitle: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialBreakingNewsTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialBreakingNewsTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let breakingNewsText: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .bold, fontSize: 21, lineHeight: 24, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let breakingNewsUpperTitle: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 13, lineHeight: 13, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let breakingNewsLowerTitle: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 23, lineHeight: 21, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: AdvertorialBreakingNewsTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let breakingNewsText: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .bold, fontSize: 21, lineHeight: 24, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let breakingNewsUpperTitle: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 17, lineHeight: 12, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let breakingNewsLowerTitle: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 30, lineHeight: 21, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
