/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.4.2
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Tab
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.sportbild.components.tab

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Tab Design Tokens
 *
 * Usage:
 *   TabTokens.Colors.Light.primaryBgIdle
 *   TabTokens.Sizing.Compact.height
 *   TabTokens.Density.Default.contentGap
 */
object TabTokens {

    // ══════════════════════════════════════════════════════════════
    // COLORS
    // ══════════════════════════════════════════════════════════════
    object Colors {
        /**
         * Returns color tokens for the current theme.
         * Automatically resolves to Light or Dark based on DesignSystemTheme.isDarkTheme
         *
         * Usage:
         *   val bgColor = TabTokens.Colors.current().primaryBgIdle
         */
        @Composable
        fun current(): ColorTokens = if (DesignSystemTheme.isDarkTheme) Dark else Light

        /**
         * Interface for color tokens
         */
        interface ColorTokens {
            val appBottomTabBarBgColor: Color
        }

        object Light : ColorTokens {
            override val appBottomTabBarBgColor = Color(0xFFFFFFFF)
        }
        object Dark : ColorTokens {
            override val appBottomTabBarBgColor = Color(0xFF0C2F61)
        }
    }

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = TabTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val tabLabelFontSize: TextUnit
            val iosTabbarHeightSize: Dp
            val androidTabbarHeightSize: Dp
            val tabLabelFontSizeLine: TextUnit
            val appsTabsLabelFontSize: TextUnit
            val appsTabsLabelLineHeight: TextUnit
            val topBarTabItemHeightSize: Dp
        }

        object Compact : SizingTokens {
            override val tabLabelFontSize = 16.sp
            override val iosTabbarHeightSize = 49.dp
            override val androidTabbarHeightSize = 56.dp
            override val tabLabelFontSizeLine = 12.sp
            override val appsTabsLabelFontSize = 12.sp
            override val appsTabsLabelLineHeight = 14.4.sp
            override val topBarTabItemHeightSize = 44.dp
        }
        object Medium : SizingTokens {
            override val tabLabelFontSize = 16.sp
            override val iosTabbarHeightSize = 49.dp
            override val androidTabbarHeightSize = 74.dp
            override val tabLabelFontSizeLine = 16.sp
            override val appsTabsLabelFontSize = 16.sp
            override val appsTabsLabelLineHeight = 23.4.sp
            override val topBarTabItemHeightSize = 44.dp
        }
        object Expanded : SizingTokens {
            override val tabLabelFontSize = 16.sp
            override val iosTabbarHeightSize = 49.dp
            override val androidTabbarHeightSize = 74.dp
            override val tabLabelFontSizeLine = 16.sp
            override val appsTabsLabelFontSize = 16.sp
            override val appsTabsLabelLineHeight = 23.4.sp
            override val topBarTabItemHeightSize = 44.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = TabTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val tabLabel: DesignTextStyle
            val appBottomBarLabelDefault: DesignTextStyle
            val appBottomBarLabelActive: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val tabLabel = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 16.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val appBottomBarLabelDefault = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Normal, fontSize = 12.sp, lineHeight = 14.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appBottomBarLabelActive = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Bold, fontSize = 12.sp, lineHeight = 14.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val tabLabel = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 16.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val appBottomBarLabelDefault = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Normal, fontSize = 16.sp, lineHeight = 23.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appBottomBarLabelActive = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 23.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val tabLabel = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 16.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val appBottomBarLabelDefault = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Normal, fontSize = 16.sp, lineHeight = 23.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appBottomBarLabelActive = DesignTextStyle(fontFamily = "Inter", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 23.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
    }
}
