// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.3.11
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Dropdown
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Advertorial Dropdown Design Tokens
///
/// Usage:
///   AdvertorialDropdownTokens.Colors.light.primaryBgIdle
///   AdvertorialDropdownTokens.Sizing.compact.height
///   AdvertorialDropdownTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialDropdownTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialDropdownSizingTokens: Sendable {
        var dropDownBorderRadius: CGFloat { get }
        var dropDownItemStackSpace: CGFloat { get }
        var dropDownItemInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialDropdownSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialDropdownSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let dropDownBorderRadius: CGFloat = 4
            public let dropDownItemStackSpace: CGFloat = 8
            public let dropDownItemInlineSpace: CGFloat = 12
        }

        public struct Regular: AdvertorialDropdownSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let dropDownBorderRadius: CGFloat = 4
            public let dropDownItemStackSpace: CGFloat = 8
            public let dropDownItemInlineSpace: CGFloat = 16
        }
    }
}
