// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Kicker
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Kicker Design Tokens
///
/// Usage:
///   KickerTokens.Colors.light.primaryBgIdle
///   KickerTokens.Sizing.compact.height
///   KickerTokens.Density.current(for: theme.density).contentGap
public enum KickerTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol KickerColorTokens: Sendable {
        var kickerBgColorOnSurface: Color { get }
        var kickerFitbookBgColor: Color { get }
        var kickerPetbookBgColor: Color { get }
        var kickerMyhomebookBgColor: Color { get }
        var kickerTravelbookBgColor: Color { get }
        var kickerTechbookBgColor: Color { get }
        var kickerKaufberaterBgColor: Color { get }
        var kickerCobiBgColor: Color { get }
        var kickerAubiBgColor: Color { get }
        var kickerSpobiBgColor: Color { get }
        var kickerBzBgColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any KickerColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: KickerColorTokens {
            public static let shared = Light()
            private init() {}
            public let kickerBgColorOnSurface: Color = Color(hex: 0x174482)
            public let kickerFitbookBgColor: Color = Color(hex: 0xFF97B7)
            public let kickerPetbookBgColor: Color = Color(hex: 0xB9DB91)
            public let kickerMyhomebookBgColor: Color = Color(hex: 0x66CCCC)
            public let kickerTravelbookBgColor: Color = Color(hex: 0x8EF0ED)
            public let kickerTechbookBgColor: Color = Color(hex: 0x93E4FF)
            public let kickerKaufberaterBgColor: Color = Color(hex: 0x55476E)
            public let kickerCobiBgColor: Color = Color(hex: 0xDC231C)
            public let kickerAubiBgColor: Color = Color(hex: 0xF00000)
            public let kickerSpobiBgColor: Color = Color(hex: 0x174482)
            public let kickerBzBgColor: Color = Color(hex: 0xE3001B)
        }

        public struct Dark: KickerColorTokens {
            public static let shared = Dark()
            private init() {}
            public let kickerBgColorOnSurface: Color = Color(hex: 0xC3C9DB)
            public let kickerFitbookBgColor: Color = Color(hex: 0xFF97B7)
            public let kickerPetbookBgColor: Color = Color(hex: 0xB9DB91)
            public let kickerMyhomebookBgColor: Color = Color(hex: 0x66CCCC)
            public let kickerTravelbookBgColor: Color = Color(hex: 0x8EF0ED)
            public let kickerTechbookBgColor: Color = Color(hex: 0x93E4FF)
            public let kickerKaufberaterBgColor: Color = Color(hex: 0x55476E)
            public let kickerCobiBgColor: Color = Color(hex: 0xDC231C)
            public let kickerAubiBgColor: Color = Color(hex: 0xF00000)
            public let kickerSpobiBgColor: Color = Color(hex: 0x174482)
            public let kickerBzBgColor: Color = Color(hex: 0xE3001B)
        }
    }
}
