// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.2
// Generated by Style Dictionary v5.1.4
//
// Context: Component: ToggleSwitch
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial ToggleSwitch Design Tokens
///
/// Usage:
///   AdvertorialToggleSwitchTokens.Colors.light.primaryBgIdle
///   AdvertorialToggleSwitchTokens.Sizing.compact.height
///   AdvertorialToggleSwitchTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialToggleSwitchTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialToggleSwitchSizingTokens: Sendable {
        var appToggleItemLabelFontSize: CGFloat { get }
        var appToggleItemLabelLineHeight: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialToggleSwitchSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialToggleSwitchSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let appToggleItemLabelFontSize: CGFloat = 14
            public let appToggleItemLabelLineHeight: CGFloat = 14.1
        }

        public struct Regular: AdvertorialToggleSwitchSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let appToggleItemLabelFontSize: CGFloat = 18
            public let appToggleItemLabelLineHeight: CGFloat = 18.2
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialToggleSwitchTypographyTokens: Sendable {
        var appToogleItemLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialToggleSwitchTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialToggleSwitchTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let appToogleItemLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 14, lineHeight: 14.1, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }

        public struct Regular: AdvertorialToggleSwitchTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let appToogleItemLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .heavy, fontSize: 18, lineHeight: 18.2, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }
    }
}
