// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Drawers
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Drawers Design Tokens
///
/// Usage:
///   DrawersTokens.Colors.light.primaryBgIdle
///   DrawersTokens.Sizing.compact.height
///   DrawersTokens.Density.current(for: theme.density).contentGap
public enum DrawersTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol DrawersSizingTokens: Sendable {
        var mobileMenuDrawerStackSpace: CGFloat { get }
        var mobileMenuDrawerLeftInlineSpace: CGFloat { get }
        var mobileMenuDrawerRightInlineSpace: CGFloat { get }
        var mobileMenuDrawerMaxWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any DrawersSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: DrawersSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let mobileMenuDrawerStackSpace: CGFloat = 20
            public let mobileMenuDrawerLeftInlineSpace: CGFloat = 20
            public let mobileMenuDrawerRightInlineSpace: CGFloat = 16
            public let mobileMenuDrawerMaxWidthSize: CGFloat = 400
        }

        public struct Regular: DrawersSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let mobileMenuDrawerStackSpace: CGFloat = 20
            public let mobileMenuDrawerLeftInlineSpace: CGFloat = 20
            public let mobileMenuDrawerRightInlineSpace: CGFloat = 16
            public let mobileMenuDrawerMaxWidthSize: CGFloat = 400
        }
    }
}
