// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Dropdown
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Dropdown Design Tokens
///
/// Usage:
///   DropdownTokens.Colors.light.primaryBgIdle
///   DropdownTokens.Sizing.compact.height
///   DropdownTokens.Density.current(for: theme.density).contentGap
public enum DropdownTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol DropdownColorTokens: Sendable {
        var dropdownBgColorHover: Color { get }
        var dropdownBgColorIdle: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any DropdownColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: DropdownColorTokens {
            public static let shared = Light()
            private init() {}
            public let dropdownBgColorHover: Color = Color(hex: 0xEFF1F5)
            public let dropdownBgColorIdle: Color = Color(hex: 0xFFFFFF)
        }

        public struct Dark: DropdownColorTokens {
            public static let shared = Dark()
            private init() {}
            public let dropdownBgColorHover: Color = Color(hex: 0x174482)
            public let dropdownBgColorIdle: Color = Color(hex: 0x113B72)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol DropdownSizingTokens: Sendable {
        var dropDownBorderRadius: CGFloat { get }
        var dropDownItemStackSpace: CGFloat { get }
        var dropDownItemInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any DropdownSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: DropdownSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let dropDownBorderRadius: CGFloat = 4
            public let dropDownItemStackSpace: CGFloat = 8
            public let dropDownItemInlineSpace: CGFloat = 12
        }

        public struct Regular: DropdownSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let dropDownBorderRadius: CGFloat = 4
            public let dropDownItemStackSpace: CGFloat = 8
            public let dropDownItemInlineSpace: CGFloat = 16
        }
    }
}
