/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Teaser
Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.sportbild.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import com.bild.designsystem.shared.ShadowStyle
import com.bild.designsystem.shared.DropShadow

/**
 * Teaser Design Tokens
 *
 * Usage:
 *   TeaserTokens.Colors.Light.primaryBgIdle
 *   TeaserTokens.Sizing.Compact.height
 *   TeaserTokens.Density.Default.contentGap
 */
object TeaserTokens {

    // ══════════════════════════════════════════════════════════════
    // COLORS
    // ══════════════════════════════════════════════════════════════
    object Colors {
        /**
         * Returns color tokens for the current theme.
         * Automatically resolves to Light or Dark based on DesignSystemTheme.isDarkTheme
         *
         * Usage:
         *   val bgColor = TeaserTokens.Colors.current().primaryBgIdle
         */
        @Composable
        fun current(): ColorTokens = if (DesignSystemTheme.isDarkTheme) Dark else Light

        /**
         * Interface for color tokens
         */
        interface ColorTokens {
            val teaserHoverOpacity: Float
            val teaserTitleBgGradientStart: Color
            val teaserTitleBgGradientStop: Color
        }

        object Light : ColorTokens {
            override val teaserHoverOpacity = 0.8f
            override val teaserTitleBgGradientStart = Color(0xB30B2647)
            override val teaserTitleBgGradientStop = Color(0x000B2647)
        }
        object Dark : ColorTokens {
            override val teaserHoverOpacity = 0.8f
            override val teaserTitleBgGradientStart = Color(0xB30B2647)
            override val teaserTitleBgGradientStop = Color(0x000B2647)
        }
    }

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = TeaserTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val teaserTitleInlineLeftSpace: Dp
            val teaserTitleStackSpace: Dp
            val mQteaserHeadlineFontSize: TextUnit
            val mQteaserHeadlineFontWeight: Int
            val mQteaserHeadlineLineHeight: TextUnit
            val mqTeaserTitleInlineSpace: Dp
            val aTeaserKickerFontSize: TextUnit
            val aTeaserHeadlineFontSize: TextUnit
            val aTeaserKickerLineHeight: TextUnit
            val aTeaserHeadlineLineHeight: TextUnit
            val aTeaserTitleInlineSpace: Dp
            val teaserTitleGapSpace: Dp
            val stdTeaserImageTitleGapSpace: Dp
            val stdTeaserBadgesMarginSpace: Dp
            val stdTeaserKickerHeadlineStackSpace: Dp
            val teaserKickerBgInlineSpace: Dp
            val teaserKickerBgStackSpace: Dp
            val quadHeadlineFontSize: TextUnit
            val quadKickerFontSize: TextUnit
            val quadHeadlineLineHeight: TextUnit
            val qTeaserTitleInlineSpace: Dp
            val teaserBadgesMarginSpace: Dp
            val teaserBadgesHeightSizeLg: Dp
            val teaserTitleBottomStackSpace: Dp
            val teaserBadgesHeightSizeSm: Dp
            val bildPlayTeaserWidthSize: Dp
            val teaserLayoutGridSpace: Dp
            val superAteaserTitleInlineSpace: Dp
            val bTeaserTitleInlineSpace: Dp
        }

        object Compact : SizingTokens {
            override val teaserTitleInlineLeftSpace = 12.dp
            override val teaserTitleStackSpace = 4.dp
            override val mQteaserHeadlineFontSize = 21.sp
            override val mQteaserHeadlineFontWeight = 700
            override val mQteaserHeadlineLineHeight = 23.1.sp
            override val mqTeaserTitleInlineSpace = 12.dp
            override val aTeaserKickerFontSize = 16.sp
            override val aTeaserHeadlineFontSize = 30.sp
            override val aTeaserKickerLineHeight = 16.sp
            override val aTeaserHeadlineLineHeight = 30.sp
            override val aTeaserTitleInlineSpace = 12.dp
            override val teaserTitleGapSpace = 4.dp
            override val stdTeaserImageTitleGapSpace = 4.dp
            override val stdTeaserBadgesMarginSpace = 4.dp
            override val stdTeaserKickerHeadlineStackSpace = 2.dp
            override val teaserKickerBgInlineSpace = 6.dp
            override val teaserKickerBgStackSpace = 2.dp
            override val quadHeadlineFontSize = 42.sp
            override val quadKickerFontSize = 20.sp
            override val quadHeadlineLineHeight = 42.sp
            override val qTeaserTitleInlineSpace = 12.dp
            override val teaserBadgesMarginSpace = 8.dp
            override val teaserBadgesHeightSizeLg = 32.dp
            override val teaserTitleBottomStackSpace = 12.dp
            override val teaserBadgesHeightSizeSm = 24.dp
            override val bildPlayTeaserWidthSize = 145.dp
            override val teaserLayoutGridSpace = 12.dp
            override val superAteaserTitleInlineSpace = 24.dp
            override val bTeaserTitleInlineSpace = 16.dp
        }
        object Medium : SizingTokens {
            override val teaserTitleInlineLeftSpace = 0.dp
            override val teaserTitleStackSpace = 4.dp
            override val mQteaserHeadlineFontSize = 30.sp
            override val mQteaserHeadlineFontWeight = 700
            override val mQteaserHeadlineLineHeight = 34.5.sp
            override val mqTeaserTitleInlineSpace = 12.dp
            override val aTeaserKickerFontSize = 26.sp
            override val aTeaserHeadlineFontSize = 44.sp
            override val aTeaserKickerLineHeight = 26.sp
            override val aTeaserHeadlineLineHeight = 50.6.sp
            override val aTeaserTitleInlineSpace = 16.dp
            override val teaserTitleGapSpace = 4.dp
            override val stdTeaserImageTitleGapSpace = 6.dp
            override val stdTeaserBadgesMarginSpace = 8.dp
            override val stdTeaserKickerHeadlineStackSpace = 2.dp
            override val teaserKickerBgInlineSpace = 6.dp
            override val teaserKickerBgStackSpace = 2.dp
            override val quadHeadlineFontSize = 60.sp
            override val quadKickerFontSize = 26.sp
            override val quadHeadlineLineHeight = 69.sp
            override val qTeaserTitleInlineSpace = 24.dp
            override val teaserBadgesMarginSpace = 8.dp
            override val teaserBadgesHeightSizeLg = 32.dp
            override val teaserTitleBottomStackSpace = 16.dp
            override val teaserBadgesHeightSizeSm = 32.dp
            override val bildPlayTeaserWidthSize = 169.dp
            override val teaserLayoutGridSpace = 12.dp
            override val superAteaserTitleInlineSpace = 24.dp
            override val bTeaserTitleInlineSpace = 16.dp
        }
        object Expanded : SizingTokens {
            override val teaserTitleInlineLeftSpace = 0.dp
            override val teaserTitleStackSpace = 6.dp
            override val mQteaserHeadlineFontSize = 34.sp
            override val mQteaserHeadlineFontWeight = 700
            override val mQteaserHeadlineLineHeight = 39.1.sp
            override val mqTeaserTitleInlineSpace = 12.dp
            override val aTeaserKickerFontSize = 26.sp
            override val aTeaserHeadlineFontSize = 50.sp
            override val aTeaserKickerLineHeight = 26.sp
            override val aTeaserHeadlineLineHeight = 57.6.sp
            override val aTeaserTitleInlineSpace = 16.dp
            override val teaserTitleGapSpace = 4.dp
            override val stdTeaserImageTitleGapSpace = 6.dp
            override val stdTeaserBadgesMarginSpace = 8.dp
            override val stdTeaserKickerHeadlineStackSpace = 2.dp
            override val teaserKickerBgInlineSpace = 6.dp
            override val teaserKickerBgStackSpace = 2.dp
            override val quadHeadlineFontSize = 80.sp
            override val quadKickerFontSize = 26.sp
            override val quadHeadlineLineHeight = 88.sp
            override val qTeaserTitleInlineSpace = 24.dp
            override val teaserBadgesMarginSpace = 8.dp
            override val teaserBadgesHeightSizeLg = 40.dp
            override val teaserTitleBottomStackSpace = 16.dp
            override val teaserBadgesHeightSizeSm = 32.dp
            override val bildPlayTeaserWidthSize = 193.dp
            override val teaserLayoutGridSpace = 16.dp
            override val superAteaserTitleInlineSpace = 24.dp
            override val bTeaserTitleInlineSpace = 16.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // EFFECTS (Shadows)
    // ══════════════════════════════════════════════════════════════
    object Effects {
        /**
         * Returns effects tokens for the current theme.
         * Automatically resolves to Light or Dark based on DesignSystemTheme.isDarkTheme
         *
         * Usage:
         *   val shadow = TeaserTokens.Effects.current().menuShadow
         */
        @Composable
        fun current(): EffectsTokens = if (DesignSystemTheme.isDarkTheme) Dark else Light

        /**
         * Interface for effects tokens (ShadowStyle composites)
         */
        interface EffectsTokens {
            val teaserHeadlinesShadow: ShadowStyle
        }

        object Light : EffectsTokens {
            override val teaserHeadlinesShadow = ShadowStyle(listOf(DropShadow(color = Color.Black.copy(alpha = 0.60f), offsetX = 0f, offsetY = 2f, blur = 8f, spread = 0f)))
        }
        object Dark : EffectsTokens {
            override val teaserHeadlinesShadow = ShadowStyle(listOf(DropShadow(color = Color.Black.copy(alpha = 0.60f), offsetX = 0f, offsetY = 2f, blur = 8f, spread = 0f)))
        }
    }
}
