// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Video
Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Advertorial Video Design Tokens
///
/// Usage:
///   AdvertorialVideoTokens.Colors.light.primaryBgIdle
///   AdvertorialVideoTokens.Sizing.compact.height
///   AdvertorialVideoTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialVideoTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialVideoSizingTokens: Sendable {
        var videoTimeBadgeCornerSize: CGFloat { get }
        var videoTimeBadgeFontSize: CGFloat { get }
        var videoTimeBadgeSize: CGFloat { get }
        var videoRedPlayIconWidthSize: CGFloat { get }
        var videoRedPlayIconHeightSize: CGFloat { get }
        var videoBadgeTimeLineHeight: CGFloat { get }
        var videoSkeletonContainerHeight: CGFloat { get }
        var videoFrameInlineSpace: CGFloat { get }
        var verticalVideoMockHeadlineFontSize: CGFloat { get }
        var videoAdBadgeFontSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialVideoSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialVideoSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let videoTimeBadgeCornerSize: CGFloat = 2
            public let videoTimeBadgeFontSize: CGFloat = 16
            public let videoTimeBadgeSize: CGFloat = 24
            public let videoRedPlayIconWidthSize: CGFloat = 8
            public let videoRedPlayIconHeightSize: CGFloat = 10
            public let videoBadgeTimeLineHeight: CGFloat = 21
            public let videoSkeletonContainerHeight: CGFloat = 180
            public let videoFrameInlineSpace: CGFloat = 0
            public let verticalVideoMockHeadlineFontSize: CGFloat = 22
            public let videoAdBadgeFontSize: CGFloat = 14
        }

        public struct Regular: AdvertorialVideoSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let videoTimeBadgeCornerSize: CGFloat = 2
            public let videoTimeBadgeFontSize: CGFloat = 18
            public let videoTimeBadgeSize: CGFloat = 40
            public let videoRedPlayIconWidthSize: CGFloat = 14
            public let videoRedPlayIconHeightSize: CGFloat = 18
            public let videoBadgeTimeLineHeight: CGFloat = 23.8
            public let videoSkeletonContainerHeight: CGFloat = 464
            public let videoFrameInlineSpace: CGFloat = 16
            public let verticalVideoMockHeadlineFontSize: CGFloat = 32
            public let videoAdBadgeFontSize: CGFloat = 16
        }
    }
}
