// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.3
// Generated by Style Dictionary v5.1.4
//
// Context: Component: LiveTicker
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial LiveTicker Design Tokens
///
/// Usage:
///   AdvertorialLiveTickerTokens.Colors.light.primaryBgIdle
///   AdvertorialLiveTickerTokens.Sizing.compact.height
///   AdvertorialLiveTickerTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialLiveTickerTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialLiveTickerSizingTokens: Sendable {
        var liveTickerHeadlinesFontSize: CGFloat { get }
        var timeStampFontFamily: String { get }
        var liveTickerTimeStampFontSize: CGFloat { get }
        var liveTickerTimeHeadlineStackSpace: CGFloat { get }
        var liveTickerSliderItemWidthMaxSize: CGFloat { get }
        var liveTickerAppCardHeightSize: CGFloat { get }
        var liveTickerAppCardWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialLiveTickerSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialLiveTickerSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let liveTickerHeadlinesFontSize: CGFloat = 22
            public let timeStampFontFamily: String = "Gotham XNarrow"
            public let liveTickerTimeStampFontSize: CGFloat = 14
            public let liveTickerTimeHeadlineStackSpace: CGFloat = 4
            public let liveTickerSliderItemWidthMaxSize: CGFloat = 257
            public let liveTickerAppCardHeightSize: CGFloat = 96
            public let liveTickerAppCardWidthSize: CGFloat = 250
        }

        public struct Regular: AdvertorialLiveTickerSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let liveTickerHeadlinesFontSize: CGFloat = 32
            public let timeStampFontFamily: String = "Gotham XNarrow"
            public let liveTickerTimeStampFontSize: CGFloat = 16
            public let liveTickerTimeHeadlineStackSpace: CGFloat = 4
            public let liveTickerSliderItemWidthMaxSize: CGFloat = 537
            public let liveTickerAppCardHeightSize: CGFloat = 128
            public let liveTickerAppCardWidthSize: CGFloat = 300
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialLiveTickerTypographyTokens: Sendable {
        var liveTickerHeadline: TextStyle { get }
        var liveTickerTimeStamp: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialLiveTickerTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialLiveTickerTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let liveTickerHeadline: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .semibold, fontSize: 22, lineHeight: 22, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let liveTickerTimeStamp: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: AdvertorialLiveTickerTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let liveTickerHeadline: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .semibold, fontSize: 32, lineHeight: 32, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let liveTickerTimeStamp: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
