// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.2
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Breadcrumb
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Breadcrumb Design Tokens
///
/// Usage:
///   BildBreadcrumbTokens.Colors.light.primaryBgIdle
///   BildBreadcrumbTokens.Sizing.compact.height
///   BildBreadcrumbTokens.Density.current(for: theme.density).contentGap
public enum BildBreadcrumbTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol BildBreadcrumbColorTokens: Sendable {
        var breadcrumbTextColorIdle: Color { get }
        var breadcrumbTextColorHover: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildBreadcrumbColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildBreadcrumbColorTokens {
            public static let shared = Light()
            private init() {}
            public let breadcrumbTextColorIdle: Color = Color(hex: 0x565A5F)
            public let breadcrumbTextColorHover: Color = Color(hex: 0x222628)
        }

        public struct Dark: BildBreadcrumbColorTokens {
            public static let shared = Dark()
            private init() {}
            public let breadcrumbTextColorIdle: Color = Color(hex: 0xA6ABB0)
            public let breadcrumbTextColorHover: Color = Color(hex: 0xF2F4F5)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildBreadcrumbSizingTokens: Sendable {
        var breadcrumbFontSize: CGFloat { get }
        var breadcrumbFontFamily: String { get }
        var breadcrumbArrowLeftInlineSpace1: CGFloat { get }
        var breadcrumbArrowRightInlineSpace2: CGFloat { get }
        var breadcrumbInlineSpace: CGFloat { get }
        var breadcrumbLineHeight: CGFloat { get }
        var breadcrumbStackSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildBreadcrumbSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildBreadcrumbSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let breadcrumbFontSize: CGFloat = 15
            public let breadcrumbFontFamily: String = "Gotham XNarrow"
            public let breadcrumbArrowLeftInlineSpace1: CGFloat = 3
            public let breadcrumbArrowRightInlineSpace2: CGFloat = 5
            public let breadcrumbInlineSpace: CGFloat = 12
            public let breadcrumbLineHeight: CGFloat = 15
            public let breadcrumbStackSpace: CGFloat = 14
        }

        public struct Regular: BildBreadcrumbSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let breadcrumbFontSize: CGFloat = 12
            public let breadcrumbFontFamily: String = "Gotham XNarrow"
            public let breadcrumbArrowLeftInlineSpace1: CGFloat = 3
            public let breadcrumbArrowRightInlineSpace2: CGFloat = 5
            public let breadcrumbInlineSpace: CGFloat = 0
            public let breadcrumbLineHeight: CGFloat = 12
            public let breadcrumbStackSpace: CGFloat = 16
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildBreadcrumbTypographyTokens: Sendable {
        var breadcrumb: TextStyle { get }
        var breadcrumbLink: TextStyle { get }
        var breadcrumbLinkHover: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildBreadcrumbTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildBreadcrumbTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let breadcrumb: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let breadcrumbLink: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .original, textDecoration: .underline )
            public let breadcrumbLinkHover: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .original, textDecoration: .underline )
        }

        public struct Regular: BildBreadcrumbTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let breadcrumb: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let breadcrumbLink: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .original, textDecoration: .underline )
            public let breadcrumbLinkHover: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .original, textDecoration: .underline )
        }
    }
}
