// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Chip
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Chip Design Tokens
///
/// Usage:
///   BildChipTokens.Colors.light.primaryBgIdle
///   BildChipTokens.Sizing.compact.height
///   BildChipTokens.Density.current(for: theme.density).contentGap
public enum BildChipTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildChipSizingTokens: Sendable {
        var chipFontSize: CGFloat { get }
        var chipInlineSpace: CGFloat { get }
        var chipStackSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildChipSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildChipSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let chipFontSize: CGFloat = 16
            public let chipInlineSpace: CGFloat = 12
            public let chipStackSpace: CGFloat = 6
        }

        public struct Regular: BildChipSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let chipFontSize: CGFloat = 18
            public let chipInlineSpace: CGFloat = 12
            public let chipStackSpace: CGFloat = 6
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildChipTypographyTokens: Sendable {
        var chipLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildChipTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildChipTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let chipLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: BildChipTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let chipLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
