// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: SpecialNavi
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Advertorial SpecialNavi Design Tokens
///
/// Usage:
///   AdvertorialSpecialNaviTokens.Colors.light.primaryBgIdle
///   AdvertorialSpecialNaviTokens.Sizing.compact.height
///   AdvertorialSpecialNaviTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialSpecialNaviTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialSpecialNaviSizingTokens: Sendable {
        var specialNaviInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialSpecialNaviSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialSpecialNaviSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let specialNaviInlineSpace: CGFloat = 24
        }

        public struct Regular: AdvertorialSpecialNaviSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let specialNaviInlineSpace: CGFloat = 32
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialSpecialNaviTypographyTokens: Sendable {
        var specialNaviItemLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialSpecialNaviTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialSpecialNaviTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let specialNaviItemLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: AdvertorialSpecialNaviTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let specialNaviItemLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
