/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Brand: Advertorial | Context: TypographyScheme Compact
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */
package com.bild.designsystem.brands.advertorial.semantic.typography

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.sp
import com.bild.designsystem.shared.DesignTypographyScheme
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Typography scheme interface for Advertorial
 * Extends DesignTypographyScheme for Dual-Axis theming compatibility
 */
@Stable
interface AdvertorialTypographyScheme : DesignTypographyScheme {
    /** Display styles are used for large, attention-grabbing text, typically in hero sections, landing pages, or promotional contexts. They emphasize hierarchy and visual impact. Font size: 40 - 40 - 72 - 120 */
    override val display1: DesignTextStyle
    /** Display styles are used for large, attention-grabbing text, typically in hero sections, landing pages, or promotional contexts. They emphasize hierarchy and visual impact. Font size: 36 - 36 - 42 - 64 */
    override val display2: DesignTextStyle
    /** Display styles are used for large, attention-grabbing text, typically in hero sections, landing pages, or promotional contexts. They emphasize hierarchy and visual impact. Font size: 28 - 28 - 32 - 40 */
    override val display3: DesignTextStyle
    /** Headlines structure content into clear sections. They are prominent but more versatile than Display styles, used across articles, teasers and modules. Font size: 48 - 48 - 72 - 100 */
    override val headline1: DesignTextStyle
    /** Headlines structure content into clear sections. They are prominent but more versatile than Display styles, used across articles, teasers and modules. This text style's token for the font size parameter changes across device sizes as follows: 40 - 40 - 48 - 64 */
    override val headline2: DesignTextStyle
    /** Headlines structure content into clear sections. They are prominent but more versatile than Display styles, used across articles, teasers and modules. This text style's font size parameter is controlled by the headline3FontSize token: 28 - 28 - 36 - 40 */
    override val headline3: DesignTextStyle
    /** Headlines structure content into clear sections. They are prominent but more versatile than Display styles, used across articles, teasers and modules. Font size: 22 - 22 - 26 - 32 */
    override val headline4: DesignTextStyle
    /** This Subheadlines text style is used in articles. They are placed under the headline at the top of an article. Subheadlines can appear in some teasers also. Font size: 24 - 24 - 32 - 36 */
    override val subheadline1: DesignTextStyle
    /** Kickers are short introductory lines placed above a headline to provide context, category, or emphasis. They support content orientation. Font size: 18 - 18 - 22 - 30 - -// * //- - currently css uses kicker0 for the naming of this text style and sequence of font size changes */
    override val kicker1: DesignTextStyle
    /** Kickers are short introductory lines placed above a headline to provide context, category, or emphasis. They support content orientation. Font size: 18 - 18 - 22 - 24 - -// * //- - currently css uses kicker1 for the naming of this text style and sequence of font size changes */
    override val kicker2: DesignTextStyle
    /** Kickers are short introductory lines placed above a headline to provide context, category, or emphasis. They support content orientation. Font size: 16 - 16 - 18 - 20 - -// * //- - currently css uses kicker2 for the naming of this text style and sequence of font size changes */
    override val kicker3: DesignTextStyle
    /** Kickers are short introductory lines placed above a headline to provide context, category, or emphasis. They support content orientation. Font size: 14 - 14 - 16 - 16 - -// * //- - currently css uses kicker3 for the naming of this text style and sequence of font size changes */
    override val kicker4: DesignTextStyle
    /** Title styles are mid-level headings, often used for module names, card headers, or section labels. They balance prominence with readability. Font size: 22 - 22 - 22 - 28 */
    override val title1: DesignTextStyle
    /** Title styles are mid-level headings, often used for module names, card headers, or section labels. They balance prominence with readability. Font size: 22 - 22 - 22 - 28 */
    override val title1uppercase: DesignTextStyle
    /** Title styles are mid-level headings, often used for module names, card headers, or section labels. They balance prominence with readability.  */
    override val title2: DesignTextStyle
    /** Title styles are mid-level headings, often used for module names, card headers, or section labels. They balance prominence with readability.  */
    override val title2uppercase: DesignTextStyle
    /** Callouts highlight key information, quotes, or important notes inside content. They stand apart from body text to draw attention. There is overlap between this text style and the title text styles. Font size: 18 - 18 - 22 - 22 */
    override val callout: DesignTextStyle
    /** Body styles are the default for running text. They prioritize readability and are optimized for long-form content across devices. Font size remains constant at 21 across device sizes. */
    override val body: DesignTextStyle
    /** Body styles are the default for running text. They prioritize readability and are optimized for long-form content across devices. Font size remains constant at 21 across device sizes. */
    override val bodyItalic: DesignTextStyle
    /** Body styles are the default for running text. They prioritize readability and are optimized for long-form content across devices. Font size remains constant at 21 across device sizes. */
    override val bodyBold: DesignTextStyle
    /** Body styles are the default for running text. They prioritize readability and are optimized for long-form content across devices. Font size remains constant at 21 across device sizes. */
    override val bodyBoldItalic: DesignTextStyle
    /** Use this text style for styling elements that are clickable text links inside body texts. This style is often found in article texts. Font size remains constant at 21 across device sizes. */
    override val textLink: DesignTextStyle
    /** Use this text style for styling elements that are clickable text links inside body texts that are using the italic style. This style is often found in article texts that need to show contrast for publications titles, specific words or names. Font size remains constant at 21 across device sizes. */
    override val textLinkItalic: DesignTextStyle
    /** Use this text style for styling elements that are clickable text links inside emphasized body texts that are using the bold or html strong style. This style is often found in article texts that need to show contrast for specific words or names. Font size remains constant at 21 across device sizes. */
    override val textLinkBold: DesignTextStyle
    /** Use this style for body text links or other text links that are in active state. Font size remains constant at 21 across device sizes. */
    override val textLinkHover: DesignTextStyle
    /** Use this style for body text links or other text links that are in active state. Font size remains constant at 21 across device sizes. */
    override val textLinkBoldHover: DesignTextStyle
    /** Footnotes are used for disclaimers, annotations, or secondary details. They are small in size and carry low visual weight. This specific style is commonly used on small two lines of text that are seen on standard teasers. The font size of this text style is similar to the label text style. This text style should be chosen when longer small descriptive texts in a small font size is needed where as the label text style should be used for shorter identifier texts. Font size: 16 - 16 - 16 - 18 */
    override val footnote1: DesignTextStyle
    /** Footnotes are used for disclaimers, annotations, or secondary details. They are small in size and carry low visual weight. This text style should be chosen when longer small descriptive texts in a small font size is needed where as the label text style should be used for shorter identifier texts. 16 - 16 - 16 - 18 */
    override val footnote1bold: DesignTextStyle
    /** Footnotes are used for disclaimers, annotations, or secondary details. They are small in size and carry low visual weight. This text style should be chosen when longer small descriptive texts in a small font size is needed where as the label text style should be used for shorter identifier texts. Font size: 12 - 12 - 12 - 16 */
    override val footnote2: DesignTextStyle
    /** Footnotes are used for disclaimers, annotations, or secondary details. They are small in size and carry low visual weight. This text style should be chosen when longer small descriptive texts in a small font size is needed where as the label text style should be used for shorter identifier texts. Font size: 12 - 12 - 12 - 16 */
    override val footnote2bold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 17 across device sizes. */
    override val label1: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 17 across device sizes. */
    override val label1bold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 17 across device sizes. */
    override val label1uppercaseBold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 15 across device sizes. */
    override val label2: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 15 across device sizes. */
    override val label2uppercase: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 15 across device sizes. */
    override val label2bold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This style used on special navi component simiiar to link lane menu items. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. The font size value remains constant at 15 across device sizes. */
    override val label2uppercaseBold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 12 across device sizes. */
    override val label3: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 12 across device sizes. Current online CSS .nav_btn- -type-list & .nav_btn__text // - -nav-btn */
    override val label3uppercase: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 12 across device sizes. */
    override val label3bold: DesignTextStyle
    /** Labels identify interface elements such as form fields, buttons, or navigation items. They ensure clarity and usability in functional contexts. This text style should be chosen when shorter small identifier texts in a small font size is needed where as the footnote text style should be used for longer descriptive texts. This text style's font size value remains constant at 12 across device sizes. */
    override val label3uppercaseBold: DesignTextStyle
    /** Use this text style for sections of text that are inside a fieldset with a quotation given by a person in an interview or a section of text from a larger body of text that need to be emphasized. */
    override val quote: DesignTextStyle
    override val testStyle: DesignTextStyle
}

/**
 * Advertorial Typography - Compact Size Class
 */
@Immutable
object AdvertorialTypographyCompact : AdvertorialTypographyScheme {
    override val display1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 39.sp,
        lineHeight = 40.sp,
        letterSpacing = (-0.5).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val display2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 35.sp,
        lineHeight = 36.sp,
        letterSpacing = (-0.5).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val display3 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 27.sp,
        lineHeight = 28.sp,
        letterSpacing = (-0.5).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 36.sp,
        lineHeight = 37.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 30.sp,
        lineHeight = 33.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline3 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Black,
        fontSize = 24.sp,
        lineHeight = 26.4.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline4 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 18.4.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val subheadline1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 18.sp,
        lineHeight = 23.4.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 17.6.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 16.sp,
        lineHeight = 17.6.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker3 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 14.sp,
        lineHeight = 15.4.sp,
        letterSpacing = 0.sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker4 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 13.2.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 22.sp,
        lineHeight = 26.4.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title1uppercase = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 22.sp,
        lineHeight = 26.4.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val title2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 14.sp,
        lineHeight = 16.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title2uppercase = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 14.sp,
        lineHeight = 16.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val callout = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 16.sp,
        lineHeight = 20.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val body = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyItalic = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyBold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyBoldItalic = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val textLink = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkItalic = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkBold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkHover = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkBoldHover = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 29.75.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val footnote1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 13.sp,
        lineHeight = 16.9.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote1bold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 13.sp,
        lineHeight = 16.9.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote2bold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 10.sp,
        lineHeight = 13.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1bold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1uppercaseBold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label2 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 15.sp,
        lineHeight = 16.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label2uppercase = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 15.sp,
        lineHeight = 16.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label2bold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 16.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label2uppercaseBold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 16.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label3 = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label3uppercase = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label3bold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label3uppercaseBold = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val quote = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 16.sp,
        lineHeight = 20.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val testStyle = DesignTextStyle(
        fontFamily = "Lucida Grande",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 1.2.sp,
        letterSpacing = 0.sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
}
