// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.1
// Generated by Style Dictionary v5.1.4
//
// Context: Component: MenuItem
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild MenuItem Design Tokens
///
/// Usage:
///   BildMenuItemTokens.Colors.light.primaryBgIdle
///   BildMenuItemTokens.Sizing.compact.height
///   BildMenuItemTokens.Density.current(for: theme.density).contentGap
public enum BildMenuItemTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol BildMenuItemColorTokens: Sendable {
        var menuItemBorderColorActive: Color { get }
        var menuItemLabelColorPrimary: Color { get }
        var menuItemLabelColorPrimaryActive: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildMenuItemColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildMenuItemColorTokens {
            public static let shared = Light()
            private init() {}
            public let menuItemBorderColorActive: Color = Color(hex: 0xDD0000)
            public let menuItemLabelColorPrimary: Color = Color(hex: 0x565A5F)
            public let menuItemLabelColorPrimaryActive: Color = Color(hex: 0x222628)
        }

        public struct Dark: BildMenuItemColorTokens {
            public static let shared = Dark()
            private init() {}
            public let menuItemBorderColorActive: Color = Color(hex: 0xFFFFFF)
            public let menuItemLabelColorPrimary: Color = Color(hex: 0xA6ABB0)
            public let menuItemLabelColorPrimaryActive: Color = Color(hex: 0xF2F4F5)
        }
    }
}
