/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.7.1
 * Generated by Style Dictionary v5.1.4
 *
 * Brand: Sportbild | Context: TypographyScheme Expanded
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */
package com.bild.designsystem.brands.sportbild.semantic.typography

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.sp
import com.bild.designsystem.shared.DesignTypographyScheme
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Sportbild Typography - Expanded Size Class
 */
@Immutable
object SportbildTypographyExpanded : SportbildTypographyScheme {
    override val display1 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 114.sp,
        lineHeight = 120.sp,
        letterSpacing = (-2).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val display2 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 61.sp,
        lineHeight = 64.sp,
        letterSpacing = (-1).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val display3 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 38.sp,
        lineHeight = 40.sp,
        letterSpacing = (-1).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline1 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 80.sp,
        lineHeight = 88.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline2 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 50.sp,
        lineHeight = 57.6.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline3 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Black,
        fontSize = 34.sp,
        lineHeight = 39.1.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val headline4 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 26.sp,
        lineHeight = 29.9.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val subheadline1 = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.Bold,
        fontSize = 26.sp,
        lineHeight = 33.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker1 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 32.sp,
        lineHeight = 35.2.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker2 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 26.sp,
        lineHeight = 28.6.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker3 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 22.sp,
        lineHeight = 24.2.sp,
        letterSpacing = 0.sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val kicker4 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 18.sp,
        lineHeight = 19.8.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title1 = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 30.sp,
        lineHeight = 33.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title1uppercase = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 30.sp,
        lineHeight = 33.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val title2 = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 20.sp,
        lineHeight = 26.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val title2uppercase = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 20.sp,
        lineHeight = 26.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val callout = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 24.sp,
        lineHeight = 31.2.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val body = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyItalic = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyBold = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val bodyBoldItalic = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val textLink = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkItalic = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkBold = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkHover = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val textLinkBoldHover = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 28.05.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.Underline
    )
    override val footnote1 = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 15.sp,
        lineHeight = 19.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote1bold = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 19.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote2 = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 13.sp,
        lineHeight = 17.03.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val footnote2bold = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Bold,
        fontSize = 13.sp,
        lineHeight = 17.03.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1bold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label1uppercaseBold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 17.sp,
        lineHeight = 20.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label2 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Normal,
        fontSize = 15.sp,
        lineHeight = 19.2.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label2uppercase = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Normal,
        fontSize = 15.sp,
        lineHeight = 19.2.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label2bold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 19.2.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label2uppercaseBold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 15.sp,
        lineHeight = 19.2.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label3 = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label3uppercase = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Normal,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val label3bold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.25).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val label3uppercaseBold = DesignTextStyle(
        fontFamily = "AntennaExtraCond",
        fontWeight = FontWeight.Bold,
        fontSize = 12.sp,
        lineHeight = 14.4.sp,
        letterSpacing = (0.5).sp,
        textCase = DesignTextCase.Uppercase,
        textDecoration = TextDecoration.None
    )
    override val quote = DesignTextStyle(
        fontFamily = "AntennaCond",
        fontWeight = FontWeight.ExtraBold,
        fontSize = 20.sp,
        lineHeight = 26.sp,
        letterSpacing = (0).sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
    override val testStyle = DesignTextStyle(
        fontFamily = "Inter",
        fontWeight = FontWeight.Normal,
        fontSize = 17.sp,
        lineHeight = 1.2.sp,
        letterSpacing = 0.sp,
        textCase = DesignTextCase.Original,
        textDecoration = TextDecoration.None
    )
}
