// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.5.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: SectionTitle
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial SectionTitle Design Tokens
///
/// Usage:
///   AdvertorialSectionTitleTokens.Colors.light.primaryBgIdle
///   AdvertorialSectionTitleTokens.Sizing.compact.height
///   AdvertorialSectionTitleTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialSectionTitleTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialSectionTitleSizingTokens: Sendable {
        var sectionTitleInnerStackBottomSpace: CGFloat { get }
        var sectionTitleHeightSize: CGFloat { get }
        var sectionTitleArrowInlineSpace: CGFloat { get }
        var sectionTitleArrowInlineSpaceActive: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialSectionTitleSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialSectionTitleSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let sectionTitleInnerStackBottomSpace: CGFloat = 12
            public let sectionTitleHeightSize: CGFloat = 32
            public let sectionTitleArrowInlineSpace: CGFloat = 5
            public let sectionTitleArrowInlineSpaceActive: CGFloat = 5
        }

        public struct Regular: AdvertorialSectionTitleSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let sectionTitleInnerStackBottomSpace: CGFloat = 12
            public let sectionTitleHeightSize: CGFloat = 40
            public let sectionTitleArrowInlineSpace: CGFloat = 5
            public let sectionTitleArrowInlineSpaceActive: CGFloat = 8
        }
    }
}
