// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: MediaPlayer
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild MediaPlayer Design Tokens
///
/// Usage:
///   BildMediaPlayerTokens.Colors.light.primaryBgIdle
///   BildMediaPlayerTokens.Sizing.compact.height
///   BildMediaPlayerTokens.Density.current(for: theme.density).contentGap
public enum BildMediaPlayerTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol BildMediaPlayerColorTokens: Sendable {
        var vidPlayerControlsAutoplayButtonBgColor: Color { get }
        var vidPlayerControlButtonsBgHoverColor: Color { get }
        var vidPlayerControlButtonsBgColorHover: Color { get }
        var vidPlayerOverlayScrimColor: Color { get }
        var audioPlayerPlayButtonBgColor: Color { get }
        var vidPlayerTooltipBgColor: Color { get }
        var vidPlayerControlButtonsBgColorPressed: Color { get }
        var vidPlayerProgressBarPreloadBgColor: Color { get }
        var vidPlayerUnmuteButtonBgColor: Color { get }
        var vidPlayerUnmuteButtonBgColorHover: Color { get }
        var vidPlayerProgressBarAdBgColor: Color { get }
        var vidPlayerFullscreenBackdropColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildMediaPlayerColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildMediaPlayerColorTokens {
            public static let shared = Light()
            private init() {}
            public let vidPlayerControlsAutoplayButtonBgColor: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerControlButtonsBgHoverColor: Color = Color(hex: 0xDD0000, alpha: 0.80)
            public let vidPlayerControlButtonsBgColorHover: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerOverlayScrimColor: Color = Color(hex: 0x000000, alpha: 0.50)
            public let audioPlayerPlayButtonBgColor: Color = Color(hex: 0xFFFFFF, alpha: 0.30)
            public let vidPlayerTooltipBgColor: Color = Color(hex: 0x000000, alpha: 0.70)
            public let vidPlayerControlButtonsBgColorPressed: Color = Color(hex: 0x000000, alpha: 0.05)
            public let vidPlayerProgressBarPreloadBgColor: Color = Color(hex: 0xFFFFFF, alpha: 0.30)
            public let vidPlayerUnmuteButtonBgColor: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerUnmuteButtonBgColorHover: Color = Color(hex: 0x000000, alpha: 0.35)
            public let vidPlayerProgressBarAdBgColor: Color = Color(hex: 0xFFBF00)
            public let vidPlayerFullscreenBackdropColor: Color = Color(hex: 0x000000)
        }

        public struct Dark: BildMediaPlayerColorTokens {
            public static let shared = Dark()
            private init() {}
            public let vidPlayerControlsAutoplayButtonBgColor: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerControlButtonsBgHoverColor: Color = Color(hex: 0xDD0000, alpha: 0.80)
            public let vidPlayerControlButtonsBgColorHover: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerOverlayScrimColor: Color = Color(hex: 0x000000, alpha: 0.50)
            public let audioPlayerPlayButtonBgColor: Color = Color(hex: 0xFFFFFF, alpha: 0.30)
            public let vidPlayerTooltipBgColor: Color = Color(hex: 0x000000, alpha: 0.70)
            public let vidPlayerControlButtonsBgColorPressed: Color = Color(hex: 0x000000, alpha: 0.05)
            public let vidPlayerProgressBarPreloadBgColor: Color = Color(hex: 0xFFFFFF, alpha: 0.30)
            public let vidPlayerUnmuteButtonBgColor: Color = Color(hex: 0x000000, alpha: 0.20)
            public let vidPlayerUnmuteButtonBgColorHover: Color = Color(hex: 0x000000, alpha: 0.35)
            public let vidPlayerProgressBarAdBgColor: Color = Color(hex: 0xFFBF00)
            public let vidPlayerFullscreenBackdropColor: Color = Color(hex: 0x000000)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildMediaPlayerSizingTokens: Sendable {
        var podcastPlayButtonSize: CGFloat { get }
        var vidPlayerBottomBarGapSpace: CGFloat { get }
        var audioPlayerHeaderStackSpace: CGFloat { get }
        var videoTimeBadgeFontFamily: String { get }
        var vidPlayerControlButtonSize: CGFloat { get }
        var vidPlayerControlButtonIconSizeHover: CGFloat { get }
        var vidPlayerTimecodeFontSize: CGFloat { get }
        var vidPlayerTimecodeContainerMinWidthSize: CGFloat { get }
        var vidPlayerProgressBarContainerHeightSize: CGFloat { get }
        var vidPlayerUnmuteButtonWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildMediaPlayerSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildMediaPlayerSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let podcastPlayButtonSize: CGFloat = 48
            public let vidPlayerBottomBarGapSpace: CGFloat = 0
            public let audioPlayerHeaderStackSpace: CGFloat = 56
            public let videoTimeBadgeFontFamily: String = "Gotham XNarrow"
            public let vidPlayerControlButtonSize: CGFloat = 42
            public let vidPlayerControlButtonIconSizeHover: CGFloat = 28
            public let vidPlayerTimecodeFontSize: CGFloat = 14
            public let vidPlayerTimecodeContainerMinWidthSize: CGFloat = 45
            public let vidPlayerProgressBarContainerHeightSize: CGFloat = 24
            public let vidPlayerUnmuteButtonWidthSize: CGFloat = 220
        }

        public struct Regular: BildMediaPlayerSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let podcastPlayButtonSize: CGFloat = 48
            public let vidPlayerBottomBarGapSpace: CGFloat = 16
            public let audioPlayerHeaderStackSpace: CGFloat = 56
            public let videoTimeBadgeFontFamily: String = "Gotham XNarrow"
            public let vidPlayerControlButtonSize: CGFloat = 42
            public let vidPlayerControlButtonIconSizeHover: CGFloat = 28
            public let vidPlayerTimecodeFontSize: CGFloat = 18
            public let vidPlayerTimecodeContainerMinWidthSize: CGFloat = 58
            public let vidPlayerProgressBarContainerHeightSize: CGFloat = 42
            public let vidPlayerUnmuteButtonWidthSize: CGFloat = 220
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildMediaPlayerTypographyTokens: Sendable {
        var podcastPlayerLabel: TextStyle { get }
        var videoAdTime: TextStyle { get }
        var videoPlayerTime: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildMediaPlayerTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildMediaPlayerTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let podcastPlayerLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let videoAdTime: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoPlayerTime: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }

        public struct Regular: BildMediaPlayerTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let podcastPlayerLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .regular, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let videoAdTime: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoPlayerTime: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }
    }
}
