/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.4.3
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Spinner
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.sportbild.components.spinner

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Spinner Design Tokens
 *
 * Usage:
 *   SpinnerTokens.Colors.Light.primaryBgIdle
 *   SpinnerTokens.Sizing.Compact.height
 *   SpinnerTokens.Density.Default.contentGap
 */
object SpinnerTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = SpinnerTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val videoSpinnerSize: Dp
            val videoSpinnerStrokeSize: Dp
            val videoSpinnerSize05x: Dp
        }

        object Compact : SizingTokens {
            override val videoSpinnerSize = 40.dp
            override val videoSpinnerStrokeSize = 2.dp
            override val videoSpinnerSize05x = 20.dp
        }
        object Medium : SizingTokens {
            override val videoSpinnerSize = 80.dp
            override val videoSpinnerStrokeSize = 4.dp
            override val videoSpinnerSize05x = 40.dp
        }
        object Expanded : SizingTokens {
            override val videoSpinnerSize = 80.dp
            override val videoSpinnerStrokeSize = 4.dp
            override val videoSpinnerSize05x = 40.dp
        }
    }
}
