// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Article
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Bild Article Design Tokens
///
/// Usage:
///   BildArticleTokens.Colors.light.primaryBgIdle
///   BildArticleTokens.Sizing.compact.height
///   BildArticleTokens.Density.current(for: theme.density).contentGap
public enum BildArticleTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildArticleSizingTokens: Sendable {
        var aricleMobile1colGridImageMarginSpace: CGFloat { get }
        var articleTopMarginSpace: CGFloat { get }
        var articleContentStackSpace: CGFloat { get }
        var articleHeadingsStackSpace: CGFloat { get }
        var articleImageLandscapeInlineSpace: CGFloat { get }
        var articleContentInlineSpace: CGFloat { get }
        var articleHeadingsInlineSpace: CGFloat { get }
        var articleImagePortaitInlineSpace: CGFloat { get }
        var articleImageContainerStackSpace: CGFloat { get }
        var articleInfoboxInlineSpace: CGFloat { get }
        var articleInfoboxStackSpace: CGFloat { get }
        var articleKickerFontSize: CGFloat { get }
        var articleHeadlineFontSize: CGFloat { get }
        var articleImageCaptionFontSize: CGFloat { get }
        var articleImageSourceFontSize: CGFloat { get }
        var articleMetaFontSize: CGFloat { get }
        var articleImageCaptionLineHeight: CGFloat { get }
        var articleImageSourceLineHeight: CGFloat { get }
        var articleMetaFontFamily: String { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildArticleSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildArticleSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let aricleMobile1colGridImageMarginSpace: CGFloat = 0
            public let articleTopMarginSpace: CGFloat = 6
            public let articleContentStackSpace: CGFloat = 12
            public let articleHeadingsStackSpace: CGFloat = 12
            public let articleImageLandscapeInlineSpace: CGFloat = 0
            public let articleContentInlineSpace: CGFloat = 16
            public let articleHeadingsInlineSpace: CGFloat = 16
            public let articleImagePortaitInlineSpace: CGFloat = 0
            public let articleImageContainerStackSpace: CGFloat = 6
            public let articleInfoboxInlineSpace: CGFloat = 16
            public let articleInfoboxStackSpace: CGFloat = 12
            public let articleKickerFontSize: CGFloat = 18
            public let articleHeadlineFontSize: CGFloat = 40
            public let articleImageCaptionFontSize: CGFloat = 16
            public let articleImageSourceFontSize: CGFloat = 16
            public let articleMetaFontSize: CGFloat = 12
            public let articleImageCaptionLineHeight: CGFloat = 19.5
            public let articleImageSourceLineHeight: CGFloat = 21
            public let articleMetaFontFamily: String = "Gotham"
        }

        public struct Regular: BildArticleSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let aricleMobile1colGridImageMarginSpace: CGFloat = 72
            public let articleTopMarginSpace: CGFloat = 12
            public let articleContentStackSpace: CGFloat = 24
            public let articleHeadingsStackSpace: CGFloat = 16
            public let articleImageLandscapeInlineSpace: CGFloat = 16
            public let articleContentInlineSpace: CGFloat = 162
            public let articleHeadingsInlineSpace: CGFloat = 16
            public let articleImagePortaitInlineSpace: CGFloat = 162
            public let articleImageContainerStackSpace: CGFloat = 12
            public let articleInfoboxInlineSpace: CGFloat = 32
            public let articleInfoboxStackSpace: CGFloat = 24
            public let articleKickerFontSize: CGFloat = 30
            public let articleHeadlineFontSize: CGFloat = 100
            public let articleImageCaptionFontSize: CGFloat = 18
            public let articleImageSourceFontSize: CGFloat = 18
            public let articleMetaFontSize: CGFloat = 16
            public let articleImageCaptionLineHeight: CGFloat = 24.75
            public let articleImageSourceLineHeight: CGFloat = 23
            public let articleMetaFontFamily: String = "Gotham"
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildArticleTypographyTokens: Sendable {
        var articleKicker: TextStyle { get }
        var articleImageCaption: TextStyle { get }
        var articleHeadline: TextStyle { get }
        var articleMetaSource: TextStyle { get }
        var articleTimeStamp: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildArticleTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildArticleTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let articleKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 18, lineHeight: 19.8, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleImageCaption: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 16, lineHeight: 19.5, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 40, lineHeight: 40, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleMetaSource: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .regular, fontSize: 16, lineHeight: 21, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleTimeStamp: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: BildArticleTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let articleKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 30, lineHeight: 30, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleImageCaption: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 18, lineHeight: 24.75, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 100, lineHeight: 100, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleMetaSource: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .regular, fontSize: 18, lineHeight: 23, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let articleTimeStamp: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
