// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.3.26
// Generated by Style Dictionary v5.1.4
//
// Context: Shared DensityDefault Struct
// Brand-independent semantic density tokens
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md
import SwiftUI

/// Default density spacing tokens (brand-independent)
///
/// Semantic density tokens for spacing adjustments.
/// Same values across all brands (BILD, SportBILD, Advertorial).
public struct DensityDefault: DesignDensityScheme {
    public static let shared = DensityDefault()
    private init() {}

    public let densityStackSpaceConst3xs: CGFloat = 2
    public let densityStackSpaceConst2xs: CGFloat = 4
    public let densityStackSpaceConstXs: CGFloat = 6
    public let densityStackSpaceConstSm: CGFloat = 8
    public let densityStackSpaceConstMd: CGFloat = 12
    public let densityStackSpaceConstLg: CGFloat = 16
    public let densityStackSpaceConstXl: CGFloat = 24
    public let densityStackSpaceConst2xl: CGFloat = 32
    public let densityXsStackSpaceRespSm: CGFloat = 8
    public let densityXsStackSpaceRespMd: CGFloat = 12
    public let densityXsStackSpaceRespLg: CGFloat = 16
    public let densityXsStackSpaceRespXl: CGFloat = 24
    public let densityXsStackSpaceResp2xl: CGFloat = 32
    public let densitySmStackSpaceRespSm: CGFloat = 8
    public let densitySmStackSpaceRespMd: CGFloat = 12
    public let densitySmStackSpaceRespLg: CGFloat = 16
    public let densitySmStackSpaceRespXl: CGFloat = 24
    public let densitySmStackSpaceResp2xl: CGFloat = 32
    public let densityMdStackSpaceRespSm: CGFloat = 12
    public let densityMdStackSpaceRespMd: CGFloat = 16
    public let densityMdStackSpaceRespLg: CGFloat = 24
    public let densityMdStackSpaceRespXl: CGFloat = 32
    public let densityMdStackSpaceResp2xl: CGFloat = 48
    public let densityLgStackSpaceRespSm: CGFloat = 16
    public let densityLgStackSpaceRespMd: CGFloat = 24
    public let densityLgStackSpaceRespLg: CGFloat = 32
    public let densityLgStackSpaceRespXl: CGFloat = 40
    public let densityLgStackSpaceResp2xl: CGFloat = 64
}
