// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.5.0
// Generated by Style Dictionary v5.1.4
//
// Context: Shared DensityDense Struct
// Brand-independent semantic density tokens
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md
import SwiftUI

/// Dense density spacing tokens (brand-independent)
///
/// Semantic density tokens for spacing adjustments.
/// Same values across all brands (BILD, SportBILD, Advertorial).
public struct DensityDense: DesignDensityScheme {
    public static let shared = DensityDense()
    private init() {}

    public let densityStackSpaceConst3xs: CGFloat = 2
    public let densityStackSpaceConst2xs: CGFloat = 2
    public let densityStackSpaceConstXs: CGFloat = 2
    public let densityStackSpaceConstSm: CGFloat = 6
    public let densityStackSpaceConstMd: CGFloat = 8
    public let densityStackSpaceConstLg: CGFloat = 12
    public let densityStackSpaceConstXl: CGFloat = 16
    public let densityStackSpaceConst2xl: CGFloat = 24
    public let densityXsStackSpaceRespSm: CGFloat = 6
    public let densityXsStackSpaceRespMd: CGFloat = 8
    public let densityXsStackSpaceRespLg: CGFloat = 12
    public let densityXsStackSpaceRespXl: CGFloat = 16
    public let densityXsStackSpaceResp2xl: CGFloat = 24
    public let densitySmStackSpaceRespSm: CGFloat = 6
    public let densitySmStackSpaceRespMd: CGFloat = 8
    public let densitySmStackSpaceRespLg: CGFloat = 12
    public let densitySmStackSpaceRespXl: CGFloat = 16
    public let densitySmStackSpaceResp2xl: CGFloat = 24
    public let densityMdStackSpaceRespSm: CGFloat = 8
    public let densityMdStackSpaceRespMd: CGFloat = 12
    public let densityMdStackSpaceRespLg: CGFloat = 16
    public let densityMdStackSpaceRespXl: CGFloat = 24
    public let densityMdStackSpaceResp2xl: CGFloat = 36
    public let densityLgStackSpaceRespSm: CGFloat = 12
    public let densityLgStackSpaceRespMd: CGFloat = 16
    public let densityLgStackSpaceRespLg: CGFloat = 24
    public let densityLgStackSpaceRespXl: CGFloat = 28
    public let densityLgStackSpaceResp2xl: CGFloat = 48
}
