// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: SwiftUI TextStyle
// Composite typography token
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Composite typography token representing a complete text style
public struct TextStyle: Equatable, Sendable {
    public let fontFamily: String
    public let fontWeight: Font.Weight
    public let fontSize: CGFloat
    public let lineHeight: CGFloat
    public let letterSpacing: CGFloat
    public let textCase: TextCase
    public let textDecoration: TextDecoration

    public init(
        fontFamily: String,
        fontWeight: Font.Weight,
        fontSize: CGFloat,
        lineHeight: CGFloat,
        letterSpacing: CGFloat,
        textCase: TextCase = .original,
        textDecoration: TextDecoration = .none
    ) {
        self.fontFamily = fontFamily
        self.fontWeight = fontWeight
        self.fontSize = fontSize
        self.lineHeight = lineHeight
        self.letterSpacing = letterSpacing
        self.textCase = textCase
        self.textDecoration = textDecoration
    }

    public enum TextCase: String, Sendable {
        case original = "ORIGINAL"
        case upper = "UPPER"
        case lower = "LOWER"
        case capitalize = "CAPITALIZE"

        var swiftUICase: Text.Case? {
            switch self {
            case .original: return nil
            case .upper: return .uppercase
            case .lower: return .lowercase
            case .capitalize: return nil
            }
        }
    }

    public enum TextDecoration: String, Sendable {
        case none = "NONE"
        case underline = "UNDERLINE"
        case strikethrough = "STRIKETHROUGH"
    }

    /// Create a SwiftUI Font from this text style with Dynamic Type support
    public func font(relativeTo textStyle: Font.TextStyle = .body) -> Font {
        Font.custom(fontFamily, size: fontSize, relativeTo: textStyle)
            .weight(fontWeight)
    }

    /// Line spacing value for SwiftUI (lineHeight - fontSize)
    public var lineSpacing: CGFloat {
        max(0, lineHeight - fontSize)
    }
}

/// View modifier for applying TextStyle
@available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, *)
public struct TextStyleModifier: ViewModifier {
    let style: TextStyle
    let relativeTo: Font.TextStyle

    public init(_ style: TextStyle, relativeTo: Font.TextStyle = .body) {
        self.style = style
        self.relativeTo = relativeTo
    }

    public func body(content: Content) -> some View {
        content
            .font(style.font(relativeTo: relativeTo))
            .tracking(style.letterSpacing)
            .lineSpacing(style.lineSpacing)
            .textCase(style.textCase.swiftUICase)
    }
}

@available(iOS 16.0, macOS 13.0, tvOS 16.0, watchOS 9.0, *)
public extension View {
    func textStyle(_ style: TextStyle, relativeTo: Font.TextStyle = .body) -> some View {
        modifier(TextStyleModifier(style, relativeTo: relativeTo))
    }
}
