/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.5.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Footer
 * Aggregated component tokens with all modes
 *
 * Brand: Bild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.bild.components.footer

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Footer Design Tokens
 *
 * Usage:
 *   FooterTokens.Colors.Light.primaryBgIdle
 *   FooterTokens.Sizing.Compact.height
 *   FooterTokens.Density.Default.contentGap
 */
object FooterTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = FooterTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val footerFontSize: TextUnit
            val footerLineHeight: TextUnit
            val footerFontFamily: String
        }

        object Compact : SizingTokens {
            override val footerFontSize = 11.sp
            override val footerLineHeight = 14.sp
            override val footerFontFamily = "Gotham XNarrow"
        }
        object Medium : SizingTokens {
            override val footerFontSize = 11.sp
            override val footerLineHeight = 14.sp
            override val footerFontFamily = "Gotham XNarrow"
        }
        object Expanded : SizingTokens {
            override val footerFontSize = 11.sp
            override val footerLineHeight = 14.sp
            override val footerFontFamily = "Gotham XNarrow"
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = FooterTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val footerLink: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val footerLink = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val footerLink = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val footerLink = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 11.sp, lineHeight = 14.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
    }
}
