// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Card
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Card Design Tokens
///
/// Usage:
///   BildCardTokens.Colors.light.primaryBgIdle
///   BildCardTokens.Sizing.compact.height
///   BildCardTokens.Density.current(for: theme.density).contentGap
public enum BildCardTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildCardSizingTokens: Sendable {
        var searchResultCardImageWidthSize: CGFloat { get }
        var searchResultCardImageHeightSizeStacked: CGFloat { get }
        var newstickerImageCardWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildCardSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildCardSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let searchResultCardImageWidthSize: CGFloat = 216
            public let searchResultCardImageHeightSizeStacked: CGFloat = 189
            public let newstickerImageCardWidthSize: CGFloat = 206
        }

        public struct Regular: BildCardSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let searchResultCardImageWidthSize: CGFloat = 260
            public let searchResultCardImageHeightSizeStacked: CGFloat = 189
            public let newstickerImageCardWidthSize: CGFloat = 206
        }
    }
}
