// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Badge
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Advertorial Badge Design Tokens
///
/// Usage:
///   AdvertorialBadgeTokens.Colors.light.primaryBgIdle
///   AdvertorialBadgeTokens.Sizing.compact.height
///   AdvertorialBadgeTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialBadgeTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialBadgeSizingTokens: Sendable {
        var badgesInnerStackSpace: CGFloat { get }
        var badgesInnerInlineSpace: CGFloat { get }
        var adLabelBadgeHeightSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialBadgeSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialBadgeSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let badgesInnerStackSpace: CGFloat = 2
            public let badgesInnerInlineSpace: CGFloat = 4
            public let adLabelBadgeHeightSize: CGFloat = 30
        }

        public struct Regular: AdvertorialBadgeSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let badgesInnerStackSpace: CGFloat = 2
            public let badgesInnerInlineSpace: CGFloat = 4
            public let adLabelBadgeHeightSize: CGFloat = 30
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialBadgeTypographyTokens: Sendable {
        var videoAdBadge: TextStyle { get }
        var videoTimeBadge: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialBadgeTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialBadgeTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let videoAdBadge: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 14, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoTimeBadge: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 16, lineHeight: 21, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: AdvertorialBadgeTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let videoAdBadge: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let videoTimeBadge: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 18, lineHeight: 23.8, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
