// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.1
// Generated by Style Dictionary v5.1.4
//
// Context: Component: InfoElement
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial InfoElement Design Tokens
///
/// Usage:
///   AdvertorialInfoElementTokens.Colors.light.primaryBgIdle
///   AdvertorialInfoElementTokens.Sizing.compact.height
///   AdvertorialInfoElementTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialInfoElementTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialInfoElementSizingTokens: Sendable {
        var infoElementTeaserBadgeHeightSize: CGFloat { get }
        var infoElementTeaserImageHeightSize: CGFloat { get }
        var infoElementTeaserImageWidthSize: CGFloat { get }
        var infoElementTeaserBadgeMarginSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialInfoElementSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialInfoElementSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let infoElementTeaserBadgeHeightSize: CGFloat = 16
            public let infoElementTeaserImageHeightSize: CGFloat = 80
            public let infoElementTeaserImageWidthSize: CGFloat = 80
            public let infoElementTeaserBadgeMarginSpace: CGFloat = 4
        }

        public struct Regular: AdvertorialInfoElementSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let infoElementTeaserBadgeHeightSize: CGFloat = 24
            public let infoElementTeaserImageHeightSize: CGFloat = 133
            public let infoElementTeaserImageWidthSize: CGFloat = 236
            public let infoElementTeaserBadgeMarginSpace: CGFloat = 8
        }
    }
}
