// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.9
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Teaser
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Teaser Design Tokens
///
/// Usage:
///   BildTeaserTokens.Colors.light.primaryBgIdle
///   BildTeaserTokens.Sizing.compact.height
///   BildTeaserTokens.Density.current(for: theme.density).contentGap
public enum BildTeaserTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol BildTeaserColorTokens: Sendable {
        var teaserHoverOpacity: CGFloat { get }
        var teaserTitleBgGradientStart: Color { get }
        var teaserTitleBgGradientStop: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildTeaserColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildTeaserColorTokens {
            public static let shared = Light()
            private init() {}
            public let teaserHoverOpacity: CGFloat = 0.8
            public let teaserTitleBgGradientStart: Color = Color(hex: 0x000000, alpha: 0.70)
            public let teaserTitleBgGradientStop: Color = Color(hex: 0x000000, alpha: 0.00)
        }

        public struct Dark: BildTeaserColorTokens {
            public static let shared = Dark()
            private init() {}
            public let teaserHoverOpacity: CGFloat = 0.8
            public let teaserTitleBgGradientStart: Color = Color(hex: 0x000000, alpha: 0.70)
            public let teaserTitleBgGradientStop: Color = Color(hex: 0x000000, alpha: 0.00)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildTeaserSizingTokens: Sendable {
        var teaserTitleInlineLeftSpace: CGFloat { get }
        var teaserTitleStackSpace: CGFloat { get }
        var mQteaserHeadlineFontSize: CGFloat { get }
        var mQteaserHeadlineLineHeight: CGFloat { get }
        var mqTeaserTitleInlineSpace: CGFloat { get }
        var aTeaserKickerFontSize: CGFloat { get }
        var aTeaserHeadlineFontSize: CGFloat { get }
        var aTeaserKickerLineHeight: CGFloat { get }
        var aTeaserHeadlineLineHeight: CGFloat { get }
        var aTeaserTitleInlineSpace: CGFloat { get }
        var teaserTitleGapSpace: CGFloat { get }
        var stdTeaserImageTitleGapSpace: CGFloat { get }
        var stdTeaserBadgesMarginSpace: CGFloat { get }
        var stdTeaserKickerHeadlineStackSpace: CGFloat { get }
        var teaserKickerBgInlineSpace: CGFloat { get }
        var teaserKickerBgStackSpace: CGFloat { get }
        var quadHeadlineFontSize: CGFloat { get }
        var quadKickerFontSize: CGFloat { get }
        var quadHeadlineLineHeight: CGFloat { get }
        var qTeaserTitleInlineSpace: CGFloat { get }
        var teaserBadgesMarginSpace: CGFloat { get }
        var teaserBadgesHeightSizeLg: CGFloat { get }
        var teaserTitleBottomStackSpace: CGFloat { get }
        var teaserBadgesHeightSizeSm: CGFloat { get }
        var bildPlayTeaserWidthSize: CGFloat { get }
        var teaserLayoutGridSpace: CGFloat { get }
        var superAteaserTitleInlineSpace: CGFloat { get }
        var bTeaserTitleInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildTeaserSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildTeaserSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let teaserTitleInlineLeftSpace: CGFloat = 12
            public let teaserTitleStackSpace: CGFloat = 4
            public let mQteaserHeadlineFontSize: CGFloat = 22
            public let mQteaserHeadlineLineHeight: CGFloat = 22
            public let mqTeaserTitleInlineSpace: CGFloat = 8
            public let aTeaserKickerFontSize: CGFloat = 16
            public let aTeaserHeadlineFontSize: CGFloat = 28
            public let aTeaserKickerLineHeight: CGFloat = 16
            public let aTeaserHeadlineLineHeight: CGFloat = 28
            public let aTeaserTitleInlineSpace: CGFloat = 8
            public let teaserTitleGapSpace: CGFloat = 4
            public let stdTeaserImageTitleGapSpace: CGFloat = 4
            public let stdTeaserBadgesMarginSpace: CGFloat = 4
            public let stdTeaserKickerHeadlineStackSpace: CGFloat = 2
            public let teaserKickerBgInlineSpace: CGFloat = 6
            public let teaserKickerBgStackSpace: CGFloat = 2
            public let quadHeadlineFontSize: CGFloat = 48
            public let quadKickerFontSize: CGFloat = 18
            public let quadHeadlineLineHeight: CGFloat = 48
            public let qTeaserTitleInlineSpace: CGFloat = 8
            public let teaserBadgesMarginSpace: CGFloat = 8
            public let teaserBadgesHeightSizeLg: CGFloat = 32
            public let teaserTitleBottomStackSpace: CGFloat = 12
            public let teaserBadgesHeightSizeSm: CGFloat = 24
            public let bildPlayTeaserWidthSize: CGFloat = 145
            public let teaserLayoutGridSpace: CGFloat = 12
            public let superAteaserTitleInlineSpace: CGFloat = 16
            public let bTeaserTitleInlineSpace: CGFloat = 8
        }

        public struct Regular: BildTeaserSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let teaserTitleInlineLeftSpace: CGFloat = 0
            public let teaserTitleStackSpace: CGFloat = 6
            public let mQteaserHeadlineFontSize: CGFloat = 40
            public let mQteaserHeadlineLineHeight: CGFloat = 40
            public let mqTeaserTitleInlineSpace: CGFloat = 8
            public let aTeaserKickerFontSize: CGFloat = 24
            public let aTeaserHeadlineFontSize: CGFloat = 64
            public let aTeaserKickerLineHeight: CGFloat = 24
            public let aTeaserHeadlineLineHeight: CGFloat = 64
            public let aTeaserTitleInlineSpace: CGFloat = 12
            public let teaserTitleGapSpace: CGFloat = 4
            public let stdTeaserImageTitleGapSpace: CGFloat = 6
            public let stdTeaserBadgesMarginSpace: CGFloat = 8
            public let stdTeaserKickerHeadlineStackSpace: CGFloat = 2
            public let teaserKickerBgInlineSpace: CGFloat = 6
            public let teaserKickerBgStackSpace: CGFloat = 2
            public let quadHeadlineFontSize: CGFloat = 100
            public let quadKickerFontSize: CGFloat = 24
            public let quadHeadlineLineHeight: CGFloat = 100
            public let qTeaserTitleInlineSpace: CGFloat = 12
            public let teaserBadgesMarginSpace: CGFloat = 8
            public let teaserBadgesHeightSizeLg: CGFloat = 40
            public let teaserTitleBottomStackSpace: CGFloat = 16
            public let teaserBadgesHeightSizeSm: CGFloat = 32
            public let bildPlayTeaserWidthSize: CGFloat = 193
            public let teaserLayoutGridSpace: CGFloat = 16
            public let superAteaserTitleInlineSpace: CGFloat = 16
            public let bTeaserTitleInlineSpace: CGFloat = 8
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildTeaserTypographyTokens: Sendable {
        var aTeaserATeaserKicker: TextStyle { get }
        var aTeaserATeaserHeadline: TextStyle { get }
        var mQteaserMQteaserKicker: TextStyle { get }
        var mQteaserMQteaserHeadline: TextStyle { get }
        var qTeaserQTeaserHeadline: TextStyle { get }
        var stdTeaserStdTeaserHeadline: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildTeaserTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildTeaserTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let aTeaserATeaserKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let aTeaserATeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 28, lineHeight: 28, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 14, lineHeight: 15.4, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 22, lineHeight: 22, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let qTeaserQTeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 48, lineHeight: 48, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let stdTeaserStdTeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .bold, fontSize: 22, lineHeight: 22, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: BildTeaserTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let aTeaserATeaserKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 24, lineHeight: 24, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let aTeaserATeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 64, lineHeight: 64, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserKicker: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 40, lineHeight: 40, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let qTeaserQTeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .black, fontSize: 100, lineHeight: 100, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let stdTeaserStdTeaserHeadline: TextStyle = TextStyle( fontFamily: "Gotham Condensed", fontWeight: .bold, fontSize: 32, lineHeight: 30, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }

    // MARK: - Effects

    /// Effects tokens protocol
    public protocol BildTeaserEffectsTokens: Sendable {
        var teaserHeadlinesShadow: ShadowStyle { get }
    }

    /// Effects accessor
    public enum Effects {
        /// Returns effects tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildTeaserEffectsTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildTeaserEffectsTokens {
            public static let shared = Light()
            private init() {}
            public let teaserHeadlinesShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.60), offsetX: 0, offsetY: 2, radius: 8, spread: 0) ])
        }

        public struct Dark: BildTeaserEffectsTokens {
            public static let shared = Dark()
            private init() {}
            public let teaserHeadlinesShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.60), offsetX: 0, offsetY: 2, radius: 8, spread: 0) ])
        }
    }
}
