// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Selection
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Selection Design Tokens
///
/// Usage:
///   SelectionTokens.Colors.light.primaryBgIdle
///   SelectionTokens.Sizing.compact.height
///   SelectionTokens.Density.current(for: theme.density).contentGap
public enum SelectionTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SelectionColorTokens: Sendable {
        var selectionBorderColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SelectionColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SelectionColorTokens {
            public static let shared = Light()
            private init() {}
            public let selectionBorderColor: Color = Color(hex: 0x4676C3)
        }

        public struct Dark: SelectionColorTokens {
            public static let shared = Dark()
            private init() {}
            public let selectionBorderColor: Color = Color(hex: 0x4676C3)
        }
    }
}
