// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.8.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Menu
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Menu Design Tokens
///
/// Usage:
///   BildMenuTokens.Colors.light.primaryBgIdle
///   BildMenuTokens.Sizing.compact.height
///   BildMenuTokens.Density.current(for: theme.density).contentGap
public enum BildMenuTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol BildMenuColorTokens: Sendable {
        var menuSurfaceColor: Color { get }
        var menuScrolledSurfaceGradientColor: Color { get }
        var menuLinkLaneSurfaceColor: Color { get }
        var menuLinkLaneLabelColor: Color { get }
        var menuLinkLaneLabelColorHover: Color { get }
        var appTopBarSurfaceColor: Color { get }
        var appTopBarIconColor: Color { get }
        var appTopBarTextColorPrimary: Color { get }
        var appTobBarTabNavBottomBorder: Color { get }
        var appTobBarTabNavBottomBorderActive: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildMenuColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildMenuColorTokens {
            public static let shared = Light()
            private init() {}
            public let menuSurfaceColor: Color = Color(hex: 0xFFFFFF)
            public let menuScrolledSurfaceGradientColor: Color = Color(hex: 0xFFFFFF, alpha: 0.95)
            public let menuLinkLaneSurfaceColor: Color = Color(hex: 0xFFFFFF)
            public let menuLinkLaneLabelColor: Color = Color(hex: 0x565A5F)
            public let menuLinkLaneLabelColorHover: Color = Color(hex: 0x222628)
            public let appTopBarSurfaceColor: Color = Color(hex: 0xFFFFFF)
            public let appTopBarIconColor: Color = Color(hex: 0x565A5F)
            public let appTopBarTextColorPrimary: Color = Color(hex: 0x222628)
            public let appTobBarTabNavBottomBorder: Color = Color(hex: 0xDDE1E2)
            public let appTobBarTabNavBottomBorderActive: Color = Color(hex: 0xDD0000)
        }

        public struct Dark: BildMenuColorTokens {
            public static let shared = Dark()
            private init() {}
            public let menuSurfaceColor: Color = Color(hex: 0x222628)
            public let menuScrolledSurfaceGradientColor: Color = Color(hex: 0x222628, alpha: 0.95)
            public let menuLinkLaneSurfaceColor: Color = Color(hex: 0x222628)
            public let menuLinkLaneLabelColor: Color = Color(hex: 0x8C9196)
            public let menuLinkLaneLabelColorHover: Color = Color(hex: 0xFFFFFF)
            public let appTopBarSurfaceColor: Color = Color(hex: 0x343C41)
            public let appTopBarIconColor: Color = Color(hex: 0xA6ABB0)
            public let appTopBarTextColorPrimary: Color = Color(hex: 0xDDE1E2)
            public let appTobBarTabNavBottomBorder: Color = Color(hex: 0x40464D)
            public let appTobBarTabNavBottomBorderActive: Color = Color(hex: 0xFFFFFF)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildMenuSizingTokens: Sendable {
        var menuItemSpace: CGFloat { get }
        var menuItemFontSize: CGFloat { get }
        var menuItemUtilFontSize: CGFloat { get }
        var menuItemUtilStackSpace: CGFloat { get }
        var menuLinkLaneHeightSize: CGFloat { get }
        var menuUtillinkItemHeightSize: CGFloat { get }
        var menuLinkItemInlineSpace: CGFloat { get }
        var menuLogoDefaultSize: CGFloat { get }
        var menuLogoScrolledSize: CGFloat { get }
        var menuSpecialNaviItemHeightSize: CGFloat { get }
        var subNavBarHeightSize: CGFloat { get }
        var menuUtilityLinksContainerHeightSize: CGFloat { get }
        var menuTopStackSpace: CGFloat { get }
        var menuLeftInlineSpace: CGFloat { get }
        var menuUtilityLinksGapSpace: CGFloat { get }
        var menuRightInlineSpace: CGFloat { get }
        var menuBottomStackSpace: CGFloat { get }
        var menuUtilityLinksDividerHeightSize: CGFloat { get }
        var menuShadowVisibility: Color { get }
        var heyInputShadowVisibility: Color { get }
        var appTopbarTitleFontSize: CGFloat { get }
        var appTopbarStageTitleLineHeight: CGFloat { get }
        var iOsappTopBarHeightSize: CGFloat { get }
        var iOsappTopBarLeftInlineSpace: CGFloat { get }
        var iOsappTopBarRightInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildMenuSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildMenuSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let menuItemSpace: CGFloat = 8
            public let menuItemFontSize: CGFloat = 15
            public let menuItemUtilFontSize: CGFloat = 12
            public let menuItemUtilStackSpace: CGFloat = 10
            public let menuLinkLaneHeightSize: CGFloat = 48
            public let menuUtillinkItemHeightSize: CGFloat = 48
            public let menuLinkItemInlineSpace: CGFloat = 4
            public let menuLogoDefaultSize: CGFloat = 56
            public let menuLogoScrolledSize: CGFloat = 56
            public let menuSpecialNaviItemHeightSize: CGFloat = 48
            public let subNavBarHeightSize: CGFloat = 42
            public let menuUtilityLinksContainerHeightSize: CGFloat = 56
            public let menuTopStackSpace: CGFloat = 6
            public let menuLeftInlineSpace: CGFloat = 8
            public let menuUtilityLinksGapSpace: CGFloat = 24
            public let menuRightInlineSpace: CGFloat = 0
            public let menuBottomStackSpace: CGFloat = 6
            public let menuUtilityLinksDividerHeightSize: CGFloat = 40
            public let menuShadowVisibility: Color = Color(hex: 0x000000, alpha: 0.10)
            public let heyInputShadowVisibility: Color = Color(hex: 0x000000, alpha: 0.00)
            public let appTopbarTitleFontSize: CGFloat = 12
            public let appTopbarStageTitleLineHeight: CGFloat = 14
            public let iOsappTopBarHeightSize: CGFloat = 44
            public let iOsappTopBarLeftInlineSpace: CGFloat = 12
            public let iOsappTopBarRightInlineSpace: CGFloat = 16
        }

        public struct Regular: BildMenuSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let menuItemSpace: CGFloat = 8
            public let menuItemFontSize: CGFloat = 15
            public let menuItemUtilFontSize: CGFloat = 12
            public let menuItemUtilStackSpace: CGFloat = 10
            public let menuLinkLaneHeightSize: CGFloat = 48
            public let menuUtillinkItemHeightSize: CGFloat = 48
            public let menuLinkItemInlineSpace: CGFloat = 4
            public let menuLogoDefaultSize: CGFloat = 148
            public let menuLogoScrolledSize: CGFloat = 56
            public let menuSpecialNaviItemHeightSize: CGFloat = 56
            public let subNavBarHeightSize: CGFloat = 42
            public let menuUtilityLinksContainerHeightSize: CGFloat = 100
            public let menuTopStackSpace: CGFloat = 8
            public let menuLeftInlineSpace: CGFloat = 16
            public let menuUtilityLinksGapSpace: CGFloat = 32
            public let menuRightInlineSpace: CGFloat = 16
            public let menuBottomStackSpace: CGFloat = 0
            public let menuUtilityLinksDividerHeightSize: CGFloat = 48
            public let menuShadowVisibility: Color = Color(hex: 0x000000, alpha: 0.00)
            public let heyInputShadowVisibility: Color = Color(hex: 0x000000, alpha: 0.10)
            public let appTopbarTitleFontSize: CGFloat = 14
            public let appTopbarStageTitleLineHeight: CGFloat = 17
            public let iOsappTopBarHeightSize: CGFloat = 48
            public let iOsappTopBarLeftInlineSpace: CGFloat = 19
            public let iOsappTopBarRightInlineSpace: CGFloat = 19
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol BildMenuTypographyTokens: Sendable {
        var appTopbarStageTitle: TextStyle { get }
        var appTopbarTabsTitle: TextStyle { get }
        var menuItemLabel: TextStyle { get }
        var menuItemUtilLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildMenuTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildMenuTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let appTopbarStageTitle: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 12, lineHeight: 14, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let appTopbarTabsTitle: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 12, lineHeight: 14, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let menuItemLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let menuItemUtilLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }

        public struct Regular: BildMenuTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let appTopbarStageTitle: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 14, lineHeight: 17, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let appTopbarTabsTitle: TextStyle = TextStyle( fontFamily: "Gotham", fontWeight: .heavy, fontSize: 14, lineHeight: 17, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let menuItemLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 15, lineHeight: 15, letterSpacing: 0, textCase: .upper, textDecoration: .none )
            public let menuItemUtilLabel: TextStyle = TextStyle( fontFamily: "Gotham XNarrow", fontWeight: .bold, fontSize: 12, lineHeight: 12, letterSpacing: 0, textCase: .upper, textDecoration: .none )
        }
    }

    // MARK: - Effects

    /// Effects tokens protocol
    public protocol BildMenuEffectsTokens: Sendable {
        var menuShadow: ShadowStyle { get }
        var heyInputShadow: ShadowStyle { get }
    }

    /// Effects accessor
    public enum Effects {
        /// Returns effects tokens for the specified theme mode
        public static func current(isDark: Bool) -> any BildMenuEffectsTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: BildMenuEffectsTokens {
            public static let shared = Light()
            private init() {}
            public let menuShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.10), offsetX: 0, offsetY: 8, radius: 10, spread: -8) ])
            public let heyInputShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.00), offsetX: 0, offsetY: 8, radius: 10, spread: -8) ])
        }

        public struct Dark: BildMenuEffectsTokens {
            public static let shared = Dark()
            private init() {}
            public let menuShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.10), offsetX: 0, offsetY: 8, radius: 10, spread: -8) ])
            public let heyInputShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.00), offsetX: 0, offsetY: 8, radius: 10, spread: -8) ])
        }
    }
}
