/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Carousel
 * Aggregated component tokens with all modes
 *
 * Brand: Bild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.brands.bild.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Carousel Design Tokens
 *
 * Usage:
 *   CarouselTokens.Colors.Light.primaryBgIdle
 *   CarouselTokens.Sizing.Compact.height
 *   CarouselTokens.Density.Default.contentGap
 */
object CarouselTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = CarouselTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val galleryTeaserTitleBottomSpace: Dp
            val galleryTeaserAppGapSpace: Dp
            val appEpaperCarouselItemFocusWidth: Dp
            val appEpaperCarouselItemDefaultWidth: Dp
            val appEpaperCarouseBeilageItemWidth: Dp
            val standardTeaserGalleryTeaserWidthWeb: Dp
            val standardTeaserGalleryTeaserWidthApp: Dp
        }

        object Compact : SizingTokens {
            override val galleryTeaserTitleBottomSpace = 28.dp
            override val galleryTeaserAppGapSpace = 0.dp
            override val appEpaperCarouselItemFocusWidth = 182.dp
            override val appEpaperCarouselItemDefaultWidth = 144.dp
            override val appEpaperCarouseBeilageItemWidth = 110.dp
            override val standardTeaserGalleryTeaserWidthWeb = 145.dp
            override val standardTeaserGalleryTeaserWidthApp = 280.dp
        }
        object Medium : SizingTokens {
            override val galleryTeaserTitleBottomSpace = 36.dp
            override val galleryTeaserAppGapSpace = 8.dp
            override val appEpaperCarouselItemFocusWidth = 240.dp
            override val appEpaperCarouselItemDefaultWidth = 172.dp
            override val appEpaperCarouseBeilageItemWidth = 172.dp
            override val standardTeaserGalleryTeaserWidthWeb = 260.dp
            override val standardTeaserGalleryTeaserWidthApp = 280.dp
        }
        object Expanded : SizingTokens {
            override val galleryTeaserTitleBottomSpace = 36.dp
            override val galleryTeaserAppGapSpace = 8.dp
            override val appEpaperCarouselItemFocusWidth = 240.dp
            override val appEpaperCarouselItemDefaultWidth = 172.dp
            override val appEpaperCarouseBeilageItemWidth = 172.dp
            override val standardTeaserGalleryTeaserWidthWeb = 300.dp
            override val standardTeaserGalleryTeaserWidthApp = 464.dp
        }
    }
}
