// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.3
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Chip
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Chip Design Tokens
///
/// Usage:
///   SportbildChipTokens.Colors.light.primaryBgIdle
///   SportbildChipTokens.Sizing.compact.height
///   SportbildChipTokens.Density.current(for: theme.density).contentGap
public enum SportbildChipTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SportbildChipColorTokens: Sendable {
        var chipBgColorHover: Color { get }
        var chipLabelColorHover: Color { get }
        var chipBgColorActive: Color { get }
        var chipBgColorIdle: Color { get }
        var chipLabelColorIdle: Color { get }
        var chipLabelColorActive: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildChipColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildChipColorTokens {
            public static let shared = Light()
            private init() {}
            public let chipBgColorHover: Color = Color(hex: 0x0C2F61)
            public let chipLabelColorHover: Color = Color(hex: 0xFFFFFF)
            public let chipBgColorActive: Color = Color(hex: 0x174482)
            public let chipBgColorIdle: Color = Color(hex: 0xD6E1F2)
            public let chipLabelColorIdle: Color = Color(hex: 0x345EA0)
            public let chipLabelColorActive: Color = Color(hex: 0xFFFFFF)
        }

        public struct Dark: SportbildChipColorTokens {
            public static let shared = Dark()
            private init() {}
            public let chipBgColorHover: Color = Color(hex: 0xD6E1F2)
            public let chipLabelColorHover: Color = Color(hex: 0x222628)
            public let chipBgColorActive: Color = Color(hex: 0xFFFFFF)
            public let chipBgColorIdle: Color = Color(hex: 0x113B72)
            public let chipLabelColorIdle: Color = Color(hex: 0x8FACDB)
            public let chipLabelColorActive: Color = Color(hex: 0x222628)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildChipSizingTokens: Sendable {
        var chipFontSize: CGFloat { get }
        var chipInlineSpace: CGFloat { get }
        var chipStackSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildChipSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildChipSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let chipFontSize: CGFloat = 16
            public let chipInlineSpace: CGFloat = 12
            public let chipStackSpace: CGFloat = 6
        }

        public struct Regular: SportbildChipSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let chipFontSize: CGFloat = 18
            public let chipInlineSpace: CGFloat = 12
            public let chipStackSpace: CGFloat = 6
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol SportbildChipTypographyTokens: Sendable {
        var chipLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildChipTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildChipTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let chipLabel: TextStyle = TextStyle( fontFamily: "Inter", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: SportbildChipTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let chipLabel: TextStyle = TextStyle( fontFamily: "Inter", fontWeight: .bold, fontSize: 18, lineHeight: 18, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
