/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Shared DensityDense Object
Brand-independent semantic density tokens
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */
package com.bild.designsystem.shared

import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Dense density spacing tokens (brand-independent)
 *
 * Semantic density tokens for spacing adjustments.
 * Same values across all brands (BILD, SportBILD, Advertorial).
 */
object DensityDense : DesignDensityScheme {
    override val densityStackSpaceConst3xs: Dp = 2.dp
    override val densityStackSpaceConst2xs: Dp = 2.dp
    override val densityStackSpaceConstXs: Dp = 2.dp
    override val densityStackSpaceConstSm: Dp = 6.dp
    override val densityStackSpaceConstMd: Dp = 8.dp
    override val densityStackSpaceConstLg: Dp = 12.dp
    override val densityStackSpaceConstXl: Dp = 16.dp
    override val densityStackSpaceConst2xl: Dp = 24.dp
    override val densityXsStackSpaceRespSm: Dp = 6.dp
    override val densityXsStackSpaceRespMd: Dp = 8.dp
    override val densityXsStackSpaceRespLg: Dp = 12.dp
    override val densityXsStackSpaceRespXl: Dp = 16.dp
    override val densityXsStackSpaceResp2xl: Dp = 24.dp
    override val densitySmStackSpaceRespSm: Dp = 6.dp
    override val densitySmStackSpaceRespMd: Dp = 8.dp
    override val densitySmStackSpaceRespLg: Dp = 12.dp
    override val densitySmStackSpaceRespXl: Dp = 16.dp
    override val densitySmStackSpaceResp2xl: Dp = 24.dp
    override val densityMdStackSpaceRespSm: Dp = 8.dp
    override val densityMdStackSpaceRespMd: Dp = 12.dp
    override val densityMdStackSpaceRespLg: Dp = 16.dp
    override val densityMdStackSpaceRespXl: Dp = 24.dp
    override val densityMdStackSpaceResp2xl: Dp = 36.dp
    override val densityLgStackSpaceRespSm: Dp = 12.dp
    override val densityLgStackSpaceRespMd: Dp = 16.dp
    override val densityLgStackSpaceRespLg: Dp = 24.dp
    override val densityLgStackSpaceRespXl: Dp = 28.dp
    override val densityLgStackSpaceResp2xl: Dp = 48.dp
}
