/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: DropShadow - Single shadow layer definition
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.shared

import androidx.compose.runtime.Immutable
import androidx.compose.ui.graphics.Color

/**
 * Single drop shadow definition
 *
 * Represents one layer of a shadow effect with all properties needed
 * for rendering in Jetpack Compose.
 *
 * @property color Shadow color (including alpha)
 * @property offsetX Horizontal offset in pixels
 * @property offsetY Vertical offset in pixels
 * @property blur Blur radius in pixels
 * @property spread Spread radius in pixels (expansion/contraction)
 */
@Immutable
data class DropShadow(
    val color: Color,
    val offsetX: Float,
    val offsetY: Float,
    val blur: Float,
    val spread: Float = 0f
)
