// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.3.11
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Datepicker
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Sportbild Datepicker Design Tokens
///
/// Usage:
///   SportbildDatepickerTokens.Colors.light.primaryBgIdle
///   SportbildDatepickerTokens.Sizing.compact.height
///   SportbildDatepickerTokens.Density.current(for: theme.density).contentGap
public enum SportbildDatepickerTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildDatepickerSizingTokens: Sendable {
        var datepickerItemDayWidthSize: CGFloat { get }
        var datepickerItemHeightSize: CGFloat { get }
        var datepickerItemYearWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildDatepickerSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildDatepickerSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let datepickerItemDayWidthSize: CGFloat = 44
            public let datepickerItemHeightSize: CGFloat = 44
            public let datepickerItemYearWidthSize: CGFloat = 77
        }

        public struct Regular: SportbildDatepickerSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let datepickerItemDayWidthSize: CGFloat = 44
            public let datepickerItemHeightSize: CGFloat = 44
            public let datepickerItemYearWidthSize: CGFloat = 77
        }
    }
}
