/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: NewsTicker
Aggregated component tokens with all modes
 *
 * Brand: Advertorial
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.advertorial.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * NewsTicker Design Tokens
 *
 * Usage:
 *   NewsTickerTokens.Colors.Light.primaryBgIdle
 *   NewsTickerTokens.Sizing.Compact.height
 *   NewsTickerTokens.Density.Default.contentGap
 */
object NewsTickerTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = NewsTickerTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val newsTickerTimeFontSize: TextUnit
            val newsTickerTimeFontWeight: Int
            val newsTickerTimeFontFamily: Dp
            val newsTickerTimeLineHeight: TextUnit
            val newsTickerContentStackSpace: Dp
            val newsTickerKickerInnerStackSpace: Dp
            val newsTickerTitlesInlineSpace: Dp
            val newsTickerBadgesInlineSpace: Dp
            val newsTickerTimeKickerStackSpace: Dp
            val newsTickerEntriesStackSpace: Dp
            val newsTickerKickerInnerInlineSpace: Dp
            val newsTickerSkeletonBottomSpace: Dp
            val newsTickerRedDotSize: Dp
            val newsTickerEntriesLeftInlineSpace: Dp
            val newsTickerLineInlineSpace: Dp
            val newsTickerAppCardHeightSize: Dp
            val newsTickerAppCardWidthSize: Dp
        }

        object Compact : SizingTokens {
            override val newsTickerTimeFontSize = 16.sp
            override val newsTickerTimeFontWeight = 700
            override val newsTickerTimeFontFamily = "Lucida Grande"
            override val newsTickerTimeLineHeight = 20.8.sp
            override val newsTickerContentStackSpace = 4.dp
            override val newsTickerKickerInnerStackSpace = 2.dp
            override val newsTickerTitlesInlineSpace = 18.dp
            override val newsTickerBadgesInlineSpace = 8.dp
            override val newsTickerTimeKickerStackSpace = 4.dp
            override val newsTickerEntriesStackSpace = 22.dp
            override val newsTickerKickerInnerInlineSpace = 4.dp
            override val newsTickerSkeletonBottomSpace = 64.dp
            override val newsTickerRedDotSize = 12.dp
            override val newsTickerEntriesLeftInlineSpace = 22.dp
            override val newsTickerLineInlineSpace = 6.dp
            override val newsTickerAppCardHeightSize = 116.dp
            override val newsTickerAppCardWidthSize = 250.dp
        }
        object Medium : SizingTokens {
            override val newsTickerTimeFontSize = 16.sp
            override val newsTickerTimeFontWeight = 700
            override val newsTickerTimeFontFamily = "Lucida Grande"
            override val newsTickerTimeLineHeight = 20.8.sp
            override val newsTickerContentStackSpace = 4.dp
            override val newsTickerKickerInnerStackSpace = 2.dp
            override val newsTickerTitlesInlineSpace = 24.dp
            override val newsTickerBadgesInlineSpace = 12.dp
            override val newsTickerTimeKickerStackSpace = 6.dp
            override val newsTickerEntriesStackSpace = 22.dp
            override val newsTickerKickerInnerInlineSpace = 4.dp
            override val newsTickerSkeletonBottomSpace = 0.dp
            override val newsTickerRedDotSize = 14.dp
            override val newsTickerEntriesLeftInlineSpace = 22.dp
            override val newsTickerLineInlineSpace = 7.dp
            override val newsTickerAppCardHeightSize = 150.dp
            override val newsTickerAppCardWidthSize = 300.dp
        }
        object Expanded : SizingTokens {
            override val newsTickerTimeFontSize = 18.sp
            override val newsTickerTimeFontWeight = 700
            override val newsTickerTimeFontFamily = "Lucida Grande"
            override val newsTickerTimeLineHeight = 23.4.sp
            override val newsTickerContentStackSpace = 4.dp
            override val newsTickerKickerInnerStackSpace = 2.dp
            override val newsTickerTitlesInlineSpace = 30.dp
            override val newsTickerBadgesInlineSpace = 16.dp
            override val newsTickerTimeKickerStackSpace = 6.dp
            override val newsTickerEntriesStackSpace = 22.dp
            override val newsTickerKickerInnerInlineSpace = 4.dp
            override val newsTickerSkeletonBottomSpace = 0.dp
            override val newsTickerRedDotSize = 16.dp
            override val newsTickerEntriesLeftInlineSpace = 22.dp
            override val newsTickerLineInlineSpace = 8.dp
            override val newsTickerAppCardHeightSize = 150.dp
            override val newsTickerAppCardWidthSize = 300.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = NewsTickerTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val newsTickerTimeStamp: DesignTextStyle
            val newsTickerKicker: DesignTextStyle
            val newsTickerHeadline: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val newsTickerTimeStamp = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 20.8.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerKicker = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 14.sp, lineHeight = 15.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Black, fontSize = 24.sp, lineHeight = 26.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val newsTickerTimeStamp = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 20.8.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerKicker = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 14.sp, lineHeight = 15.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Black, fontSize = 26.sp, lineHeight = 28.6.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val newsTickerTimeStamp = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 18.sp, lineHeight = 23.4.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerKicker = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 17.6.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val newsTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Black, fontSize = 32.sp, lineHeight = 35.2.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
    }
}
