/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.3.26
 * Generated by Style Dictionary v5.1.4
 *
 * Context: ContentBrand Enum (Dual-Axis Architecture)
 * Defines the content axis - sizing, typography, and layout tokens
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.shared

/**
 * Content brands in the BILD Design System
 *
 * Determines which sizing, typography, and layout tokens to use.
 * All brands are included, even those without their own color tokens.
 *
 * Note: Advertorial uses ColorBrand for colors but has its own sizing tokens.
 *
 * Usage:
 * ```kotlin
 * DesignSystemTheme(
 *     colorBrand = ColorBrand.Sportbild,   // Use SportBILD colors
 *     contentBrand = ContentBrand.Advertorial,  // Use Advertorial sizing
 *     darkTheme = isSystemInDarkTheme()
 * ) {
 *     // Advertorial content with SportBILD colors
 * }
 * ```
 */
enum class ContentBrand {
    /** Bild content/sizing */
    Bild,
    /** Sportbild content/sizing */
    Sportbild,
    /** Advertorial content/sizing (uses ColorBrand for colors) */
    Advertorial
}
