/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.7.7
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Unified DesignSizingScheme Interface (Dual-Axis Architecture)
 * All content brands implement this interface for polymorphic sizing access
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.shared

import androidx.compose.runtime.Stable
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.TextUnit

/**
 * Unified sizing scheme interface for the BILD Design System
 *
 * All content brands (BILD, SportBILD, Advertorial) implement this interface,
 * enabling polymorphic sizing access across brands.
 */
@Stable
interface DesignSizingScheme {
    val gridSpaceRespLg: Dp
    val gridSpaceRespXl: Dp
    val gridSpaceRespBase: Dp
    val gridSpaceRespSm: Dp
    val pageInlineSpace: Dp
    val gridSpaceConstLg: Dp
    val gridSpaceConstSm: Dp
    val layoutGuideGridColumns: Int
    val sectionSpaceBase: Dp
    val sectionSpaceLg: Dp
    val paragraphEndSpace: Dp
    val sectionSpaceSm: Dp
    val canvasMinWidthSize: Dp
    val canvasMaxWidthSize: Dp
    val canvasHeightSizeWeb: Dp
    val contentMaxWidthMedium: Dp
    val contentMaxWidthFull: Dp
    val canvasWidthSizeWeb: Dp
    val canvasWidthSizeApp: Dp
    val canvasHeightSizeApp: Dp
    val title1fontSize: TextUnit
    val title2fontSize: TextUnit
    val display1fontSize: TextUnit
    val display2fontSize: TextUnit
    val display3fontSize: TextUnit
    val headline1fontSize: TextUnit
    val headline2fontSize: TextUnit
    val headline3fontSize: TextUnit
    val headline4fontSize: TextUnit
    val bodyFontSize: TextUnit
    val label3fontSize: TextUnit
    val label2fontSize: TextUnit
    val label1fontSize: TextUnit
    val callout1fontSize: TextUnit
    val footnote1fontSize: TextUnit
    val footnote2fontSize: TextUnit
    val kicker1fontSize: TextUnit
    val kicker2fontSize: TextUnit
    val kicker3fontSize: TextUnit
    val kicker4fontSize: TextUnit
    val subheadline1fontSize: TextUnit
    val quoteFontSize: TextUnit
    val bodyFontFamily: String
    val calloutFontFamily: String
    val headlineFontFamily: String
    val footnoteFontFamily: String
    val labelFontFamily: String
    val kickerFontFamily: String
    val subheadlineFontFamily: String
    val titleFontFamily: String
    val quoteFontFamily: String
    val displayFontFamily: String
    val calloutFontWeight: Int
    val labelFontWeightBold: Int
    val labelFontWeightBook: Int
    val bodyFontWeightBook: Int
    val bodyFontWeightBold: Int
    val kickerFontWeight: Int
    val subheadlineFontWeight: Int
    val headline1fontWeight: Int
    val headline2fontWeight: Int
    val headline3fontWeight: Int
    val headline4fontWeight: Int
    val titleFontWeight: Int
    val displayFontWeight: Int
    val quoteFontWeight: Int
    val footnoteFontWeightBook: Int
    val footnoteFontWeightBold: Int
    val bodyLineHeight: TextUnit
    val kicker4lineHeight: TextUnit
    val kicker3lineHeight: TextUnit
    val kicker2lineHeight: TextUnit
    val kicker1lineHeight: TextUnit
    val label3lineHeight: TextUnit
    val label1lineHeight: TextUnit
    val label2lineHeight: TextUnit
    val display1lineHeight: TextUnit
    val display2lineHeight: TextUnit
    val display3lineHeight: TextUnit
    val title1lineHeight: TextUnit
    val title2lineHeight: TextUnit
    val quoteLineHeight: TextUnit
    val footnote1lineHeight: TextUnit
    val footnote2lineHeight: TextUnit
    val headline1lineHeight: TextUnit
    val headline2lineHeight: TextUnit
    val headline3lineHeight: TextUnit
    val headline4lineHeight: TextUnit
    val calloutLineHeight: TextUnit
    val subheadline1lineHeight: TextUnit
    val letterSpacePositiveSm: TextUnit
    val letterSpacePositiveLg: TextUnit
    val letterSpacePositiveMd: TextUnit
    val letterSpaceNone: TextUnit
    val letterSpaceNegativeSm: TextUnit
    val letterSpaceNegativeMd: TextUnit
    val letterSpaceNegativeLg: TextUnit
    val letterSpaceNegativeXs: TextUnit
    val letterSpacePositiveXs: TextUnit
    val display1letterSpace: TextUnit
    val display2letterSpace: TextUnit
    val display3letterSpace: TextUnit
    val borderRadiusXs: Dp
    val borderRadiusMd: Dp
    val borderRadiusSm: Dp
    val borderRadiusXl: Dp
    val borderRadiusLg: Dp
    val borderRadiusNone: Dp
    val borderRadiusFull: Dp
    val borderWidthThin: Dp
    val borderWidthThick: Dp
    val borderWidthHairline: Dp
    val inlineSpaceRespSm: Dp
    val inlineSpaceRespMd: Dp
    val inlineSpaceRespLg: Dp
    val inlineSpaceResp2xl: Dp
    val inlineSpaceRespXl: Dp
    val inlineSpaceConstSm: Dp
    val inlineSpaceConstMd: Dp
    val inlineSpaceConstLg: Dp
    val inlineSpaceConst2xl: Dp
    val inlineSpaceConstXl: Dp
    val inlineSpaceConstXs: Dp
    val inlineSpaceConst3xs: Dp
    val inlineSpaceConst2xs: Dp
    val gapSpaceRespXs: Dp
    val gapSpaceRespLg: Dp
    val gapSpaceRespXl: Dp
    val gapSpaceResp2xl: Dp
    val gapSpaceRespMd: Dp
    val gapSpaceRespSm: Dp
    val gapSpaceResp2xs: Dp
    val gapSpaceResp3xl: Dp
    val gapSpaceConst2xs: Dp
    val gapSpaceConstXs: Dp
    val gapSpaceConstSm: Dp
    val gapSpaceConstMd: Dp
    val gapSpaceConstLg: Dp
    val gapSpaceConstXl: Dp
    val gapSpaceConst2xl: Dp
    val gapSpaceConst3xl: Dp
    val sizeConst3xs: Dp
    val sizeConst2xs: Dp
    val sizeConstXs: Dp
    val sizeConstSm: Dp
    val sizeConstMd: Dp
    val sizeConstLg: Dp
    val sizeConstXl: Dp
    val sizeConst3xl: Dp
    val sizeConst4xl: Dp
    val sizeConst2xl: Dp
    val sizeConst4xs: Dp
    val sizeResp3xs: Dp
    val sizeResp2xs: Dp
    val sizeRespXs: Dp
    val sizeRespSm: Dp
    val sizeRespMd: Dp
    val sizeRespLg: Dp
    val sizeRespXl: Dp
    val sizeResp2xl: Dp
    val sizeResp3xl: Dp
    val sizeResp4xl: Dp
    val sizeResp4xs: Dp
}
