/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.7.7
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Unified DesignEffectsScheme Interface
 * Brand-independent: shadows only depend on light/dark mode
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.shared

import androidx.compose.runtime.Stable

/**
 * Unified effects scheme interface for the BILD Design System
 *
 * Effects (shadows) are brand-independent and only vary by color mode (light/dark).
 * This interface is implemented by EffectsLight and EffectsDark.
 *
 * Usage:
 * ```kotlin
 * @Composable
 * fun MyCard() {
 *     val effects = DesignSystemTheme.effects
 *     Box(
 *         modifier = Modifier
 *             .then(effects.shadowSoftMd.toModifier())
 *             .background(Color.White)
 *     )
 * }
 * ```
 */
@Stable
interface DesignEffectsScheme {
    /** Soft shadow - Small: Subtle surface separation */
    val shadowSoftSm: ShadowStyle
    /** Soft shadow - Medium: Cards, sheets */
    val shadowSoftMd: ShadowStyle
    /** Soft shadow - Large: Elevated cards */
    val shadowSoftLg: ShadowStyle
    /** Soft shadow - Extra Large: Prominent elevation */
    val shadowSoftXl: ShadowStyle
    /** Hard shadow - Small: Subtle focus */
    val shadowHardSm: ShadowStyle
    /** Hard shadow - Medium: Dropdowns, menus */
    val shadowHardMd: ShadowStyle
    /** Hard shadow - Large: Dialogs, modals */
    val shadowHardLg: ShadowStyle
    /** Hard shadow - Extra Large: Overlays */
    val shadowHardXl: ShadowStyle
}
