/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.7.7
 * Generated by Style Dictionary v5.1.4
 *
 * Context: DesignTextStyle - Typography composite token
 * Represents a complete text style with all typography properties
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.shared

import androidx.compose.runtime.Immutable
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.unit.sp

/**
 * Text case transformation options
 */
enum class DesignTextCase {
    Original,
    Uppercase,
    Lowercase,
    Capitalize
}

/**
 * Design System TextStyle composite token
 *
 * Contains all typography properties for a complete text style.
 * Use [toComposeTextStyle] to convert to Compose's TextStyle with font resolution.
 *
 * Usage:
 * ```kotlin
 * val style = DesignSystemTheme.typography.headline1
 * Text(
 *     text = "Hello",
 *     style = style.toComposeTextStyle(fontResolver)
 * )
 * ```
 */
@Immutable
data class DesignTextStyle(
    val fontFamily: String,
    val fontWeight: FontWeight,
    val fontSize: TextUnit,
    val lineHeight: TextUnit,
    val letterSpacing: TextUnit = 0.sp,
    val textCase: DesignTextCase = DesignTextCase.Original,
    val textDecoration: TextDecoration = TextDecoration.None
) {
    /**
     * Converts this DesignTextStyle to Compose's TextStyle
     *
     * @param fontResolver A function that resolves font family name to FontFamily
     *                     Example: { name -> FontFamily(Font(R.font.gotham_xnarrow)) }
     * @return A Compose TextStyle ready for use with Text composable
     */
    fun toComposeTextStyle(fontResolver: (String) -> FontFamily = { FontFamily.Default }): TextStyle {
        return TextStyle(
            fontFamily = fontResolver(fontFamily),
            fontWeight = fontWeight,
            fontSize = fontSize,
            lineHeight = lineHeight,
            letterSpacing = letterSpacing,
            textDecoration = textDecoration
        )
    }

    /**
     * Converts this DesignTextStyle to Compose's TextStyle using default system fonts
     */
    fun toComposeTextStyle(): TextStyle = toComposeTextStyle { FontFamily.Default }
}
