/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.3.26
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Selection
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.sportbild.components.selection

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import androidx.compose.ui.graphics.Color

/**
 * Selection Design Tokens
 *
 * Usage:
 *   SelectionTokens.Colors.Light.primaryBgIdle
 *   SelectionTokens.Sizing.Compact.height
 *   SelectionTokens.Density.Default.contentGap
 */
object SelectionTokens {

    // ══════════════════════════════════════════════════════════════
    // COLORS
    // ══════════════════════════════════════════════════════════════
    object Colors {
        /**
         * Returns color tokens for the current theme.
         * Automatically resolves to Light or Dark based on DesignSystemTheme.isDarkTheme
         *
         * Usage:
         *   val bgColor = SelectionTokens.Colors.current().primaryBgIdle
         */
        @Composable
        fun current(): ColorTokens = if (DesignSystemTheme.isDarkTheme) Dark else Light

        /**
         * Interface for color tokens
         */
        interface ColorTokens {
            val selectionBorderColor: Color
        }

        object Light : ColorTokens {
            override val selectionBorderColor = Color(0xFF4676C3)
        }
        object Dark : ColorTokens {
            override val selectionBorderColor = Color(0xFF4676C3)
        }
    }
}
