/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Menu
 * Aggregated component tokens with all modes
 *
 * Brand: Advertorial
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.advertorial.components.menu

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Menu Design Tokens
 *
 * Usage:
 *   MenuTokens.Colors.Light.primaryBgIdle
 *   MenuTokens.Sizing.Compact.height
 *   MenuTokens.Density.Default.contentGap
 */
object MenuTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = MenuTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val menuItemSpace: Dp
            val menuItemFontSize: TextUnit
            val menuItemUtilFontSize: TextUnit
            val menuItemUtilStackSpace: Dp
            val menuLinkLaneHeightSize: Dp
            val menuUtillinkItemHeightSize: Dp
            val menuLinkItemInlineSpace: Dp
            val menuLogoDefaultSize: Dp
            val menuLogoScrolledSize: Dp
            val menuSpecialNaviItemHeightSize: Dp
            val subNavBarHeightSize: Dp
            val menuUtilityLinksContainerHeightSize: Dp
            val menuTopStackSpace: Dp
            val menuLeftInlineSpace: Dp
            val menuUtilityLinksGapSpace: Dp
            val menuRightInlineSpace: Dp
            val menuBottomStackSpace: Dp
            val menuUtilityLinksDividerHeightSize: Dp
            val menuShadowVisibility: Color
            val heyInputShadowVisibility: Color
            val appTopbarTitleFontSize: TextUnit
            val appTopbarStageTitleHeight: TextUnit
            val iOsappTopBarHeightSize: Dp
            val iOsappTopBarLeftInlineSpace: Dp
            val iOsappTopBarRightInlineSpace: Dp
        }

        object Compact : SizingTokens {
            override val menuItemSpace = 8.dp
            override val menuItemFontSize = 15.sp
            override val menuItemUtilFontSize = 12.sp
            override val menuItemUtilStackSpace = 10.dp
            override val menuLinkLaneHeightSize = 48.dp
            override val menuUtillinkItemHeightSize = 48.dp
            override val menuLinkItemInlineSpace = 4.dp
            override val menuLogoDefaultSize = 56.dp
            override val menuLogoScrolledSize = 56.dp
            override val menuSpecialNaviItemHeightSize = 48.dp
            override val subNavBarHeightSize = 42.dp
            override val menuUtilityLinksContainerHeightSize = 56.dp
            override val menuTopStackSpace = 6.dp
            override val menuLeftInlineSpace = 8.dp
            override val menuUtilityLinksGapSpace = 24.dp
            override val menuRightInlineSpace = 0.dp
            override val menuBottomStackSpace = 6.dp
            override val menuUtilityLinksDividerHeightSize = 40.dp
            override val menuShadowVisibility = Color(0x1A000000)
            override val heyInputShadowVisibility = Color(0x00000000)
            override val appTopbarTitleFontSize = 12.sp
            override val appTopbarStageTitleHeight = 14.sp
            override val iOsappTopBarHeightSize = 44.dp
            override val iOsappTopBarLeftInlineSpace = 12.dp
            override val iOsappTopBarRightInlineSpace = 16.dp
        }
        object Medium : SizingTokens {
            override val menuItemSpace = 8.dp
            override val menuItemFontSize = 15.sp
            override val menuItemUtilFontSize = 12.sp
            override val menuItemUtilStackSpace = 10.dp
            override val menuLinkLaneHeightSize = 48.dp
            override val menuUtillinkItemHeightSize = 48.dp
            override val menuLinkItemInlineSpace = 4.dp
            override val menuLogoDefaultSize = 56.dp
            override val menuLogoScrolledSize = 56.dp
            override val menuSpecialNaviItemHeightSize = 48.dp
            override val subNavBarHeightSize = 42.dp
            override val menuUtilityLinksContainerHeightSize = 56.dp
            override val menuTopStackSpace = 6.dp
            override val menuLeftInlineSpace = 8.dp
            override val menuUtilityLinksGapSpace = 24.dp
            override val menuRightInlineSpace = 0.dp
            override val menuBottomStackSpace = 6.dp
            override val menuUtilityLinksDividerHeightSize = 40.dp
            override val menuShadowVisibility = Color(0x1A000000)
            override val heyInputShadowVisibility = Color(0x00000000)
            override val appTopbarTitleFontSize = 14.sp
            override val appTopbarStageTitleHeight = 17.sp
            override val iOsappTopBarHeightSize = 48.dp
            override val iOsappTopBarLeftInlineSpace = 19.dp
            override val iOsappTopBarRightInlineSpace = 19.dp
        }
        object Expanded : SizingTokens {
            override val menuItemSpace = 8.dp
            override val menuItemFontSize = 15.sp
            override val menuItemUtilFontSize = 12.sp
            override val menuItemUtilStackSpace = 10.dp
            override val menuLinkLaneHeightSize = 48.dp
            override val menuUtillinkItemHeightSize = 48.dp
            override val menuLinkItemInlineSpace = 4.dp
            override val menuLogoDefaultSize = 148.dp
            override val menuLogoScrolledSize = 56.dp
            override val menuSpecialNaviItemHeightSize = 56.dp
            override val subNavBarHeightSize = 42.dp
            override val menuUtilityLinksContainerHeightSize = 100.dp
            override val menuTopStackSpace = 8.dp
            override val menuLeftInlineSpace = 16.dp
            override val menuUtilityLinksGapSpace = 32.dp
            override val menuRightInlineSpace = 16.dp
            override val menuBottomStackSpace = 0.dp
            override val menuUtilityLinksDividerHeightSize = 48.dp
            override val menuShadowVisibility = Color(0x00000000)
            override val heyInputShadowVisibility = Color(0x1A000000)
            override val appTopbarTitleFontSize = 14.sp
            override val appTopbarStageTitleHeight = 17.sp
            override val iOsappTopBarHeightSize = 48.dp
            override val iOsappTopBarLeftInlineSpace = 19.dp
            override val iOsappTopBarRightInlineSpace = 19.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = MenuTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val appTopbarStageTitle: DesignTextStyle
            val appTopbarTabsTitle: DesignTextStyle
            val menuItemLabel: DesignTextStyle
            val menuItemUtilLabel: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val appTopbarStageTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appTopbarTabsTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 12.sp, lineHeight = 14.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 15.sp, lineHeight = 15.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemUtilLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 12.sp, lineHeight = 12.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val appTopbarStageTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 14.sp, lineHeight = 17.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appTopbarTabsTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 14.sp, lineHeight = 17.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 15.sp, lineHeight = 15.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemUtilLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 12.sp, lineHeight = 12.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val appTopbarStageTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 14.sp, lineHeight = 17.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val appTopbarTabsTitle = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.ExtraBold, fontSize = 14.sp, lineHeight = 17.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 15.sp, lineHeight = 15.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
            override val menuItemUtilLabel = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.Bold, fontSize = 12.sp, lineHeight = 12.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Uppercase, textDecoration = TextDecoration.None)
        }
    }
}
