/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: _DSysDocs
 * Aggregated component tokens with all modes
 *
 * Brand: Advertorial
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.brands.advertorial.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit

/**
 * _DSysDocs Design Tokens
 *
 * Usage:
 *   _DSysDocsTokens.Colors.Light.primaryBgIdle
 *   _DSysDocsTokens.Sizing.Compact.height
 *   _DSysDocsTokens.Density.Default.contentGap
 */
object _DSysDocsTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = _DSysDocsTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val bildDesignFrameSpace: Dp
            val dsMainContainerSpace: Dp
            val dsysDocsWidthSize: Dp
            val mainContentStageSize: Dp
            val foundationsBannerHeightSize: Dp
            val docLabelRespFontSize: TextUnit
            val dsCaptionStackSpace0p5x: Dp
            val dsCaptionStackSpace1x: Dp
            val label1responsiveLineHeight: Dp
            val _1columnMobile: Dp
            val thinBannerVerticalHeightSize: Dp
            val specsFontFamily: Dp
            val docHeaderHeightSize: Dp
        }

        object Compact : SizingTokens {
            override val bildDesignFrameSpace = 12.dp
            override val dsMainContainerSpace = 0.dp
            override val dsysDocsWidthSize = 750.dp
            override val mainContentStageSize = 750.dp
            override val foundationsBannerHeightSize = 80.dp
            override val docLabelRespFontSize = 10.sp
            override val dsCaptionStackSpace0p5x = 4.dp
            override val dsCaptionStackSpace1x = 8.dp
            override val label1responsiveLineHeight = UNRESOLVED_VariableID:18038:10774
            override val _1columnMobile = 320.dp
            override val thinBannerVerticalHeightSize = 558.dp
            override val specsFontFamily = "Gotham"
            override val docHeaderHeightSize = 144.dp
        }
        object Medium : SizingTokens {
            override val bildDesignFrameSpace = 64.dp
            override val dsMainContainerSpace = 68.dp
            override val dsysDocsWidthSize = 962.dp
            override val mainContentStageSize = 962.dp
            override val foundationsBannerHeightSize = 80.dp
            override val docLabelRespFontSize = 15.sp
            override val dsCaptionStackSpace0p5x = 6.dp
            override val dsCaptionStackSpace1x = 12.dp
            override val label1responsiveLineHeight = UNRESOLVED_VariableID:18038:10775
            override val _1columnMobile = 930.dp
            override val thinBannerVerticalHeightSize = 558.dp
            override val specsFontFamily = "Gotham"
            override val docHeaderHeightSize = 160.dp
        }
        object Expanded : SizingTokens {
            override val bildDesignFrameSpace = 64.dp
            override val dsMainContainerSpace = 68.dp
            override val dsysDocsWidthSize = 1440.dp
            override val mainContentStageSize = 1024.dp
            override val foundationsBannerHeightSize = 140.dp
            override val docLabelRespFontSize = 17.sp
            override val dsCaptionStackSpace0p5x = 8.dp
            override val dsCaptionStackSpace1x = 16.dp
            override val label1responsiveLineHeight = UNRESOLVED_VariableID:18038:10776
            override val _1columnMobile = 656.dp
            override val thinBannerVerticalHeightSize = 186.dp
            override val specsFontFamily = "Gotham"
            override val docHeaderHeightSize = 180.dp
        }
    }
}
