// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Pagination
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Pagination Design Tokens
///
/// Usage:
///   PaginationTokens.Colors.light.primaryBgIdle
///   PaginationTokens.Sizing.compact.height
///   PaginationTokens.Density.current(for: theme.density).contentGap
public enum PaginationTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol PaginationColorTokens: Sendable {
        var paginationElementColorDefault: Color { get }
        var paginationElementColorActive: Color { get }
        var galleryPaginationElementActiveOpacity: CGFloat { get }
        var scrollBarTrackBgColor: Color { get }
        var scrollBarThumbBgColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any PaginationColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: PaginationColorTokens {
            public static let shared = Light()
            private init() {}
            public let paginationElementColorDefault: Color = Color(hex: 0xC3C9DB)
            public let paginationElementColorActive: Color = Color(hex: 0x174482)
            public let galleryPaginationElementActiveOpacity: CGFloat = 1
            public let scrollBarTrackBgColor: Color = Color(hex: 0x000000, alpha: 0.10)
            public let scrollBarThumbBgColor: Color = Color(hex: 0x6A91CF)
        }

        public struct Dark: PaginationColorTokens {
            public static let shared = Dark()
            private init() {}
            public let paginationElementColorDefault: Color = Color(hex: 0xC3C9DB)
            public let paginationElementColorActive: Color = Color(hex: 0xFFFFFF)
            public let galleryPaginationElementActiveOpacity: CGFloat = 1
            public let scrollBarTrackBgColor: Color = Color(hex: 0xFFFFFF, alpha: 0.10)
            public let scrollBarThumbBgColor: Color = Color(hex: 0x6A91CF)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol PaginationSizingTokens: Sendable {
        var galleryPaginationItemHeightSize: CGFloat { get }
        var galleryPaginationContainerWebInlineSpace: CGFloat { get }
        var galleryPaginationContainerStackSpace: CGFloat { get }
        var galleryPaginationContainerAppInlineSpace: CGFloat { get }
        var scrollBarThicknessSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any PaginationSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: PaginationSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let galleryPaginationItemHeightSize: CGFloat = 4
            public let galleryPaginationContainerWebInlineSpace: CGFloat = 8
            public let galleryPaginationContainerStackSpace: CGFloat = 8
            public let galleryPaginationContainerAppInlineSpace: CGFloat = 12
            public let scrollBarThicknessSize: CGFloat = 8
        }

        public struct Regular: PaginationSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let galleryPaginationItemHeightSize: CGFloat = 4
            public let galleryPaginationContainerWebInlineSpace: CGFloat = 12
            public let galleryPaginationContainerStackSpace: CGFloat = 12
            public let galleryPaginationContainerAppInlineSpace: CGFloat = 12
            public let scrollBarThicknessSize: CGFloat = 8
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol PaginationTypographyTokens: Sendable {
        var numberedPaginationActive: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any PaginationTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: PaginationTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let numberedPaginationActive: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 17, lineHeight: 20.4, letterSpacing: 0.25, textCase: .original, textDecoration: .underline )
        }

        public struct Regular: PaginationTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let numberedPaginationActive: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 17, lineHeight: 20.4, letterSpacing: 0.25, textCase: .original, textDecoration: .underline )
        }
    }
}
