/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Separator
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.sportbild.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Separator Design Tokens
 *
 * Usage:
 *   SeparatorTokens.Colors.Light.primaryBgIdle
 *   SeparatorTokens.Sizing.Compact.height
 *   SeparatorTokens.Density.Default.contentGap
 */
object SeparatorTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = SeparatorTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val separatorThicknessSize: Dp
        }

        object Compact : SizingTokens {
            override val separatorThicknessSize = 2.dp
        }
        object Medium : SizingTokens {
            override val separatorThicknessSize = 2.dp
        }
        object Expanded : SizingTokens {
            override val separatorThicknessSize = 2.dp
        }
    }
}
