/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.0.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: IconButton
 * Aggregated component tokens with all modes
 *
 * Brand: Bild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.bild.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * IconButton Design Tokens
 *
 * Usage:
 *   IconButtonTokens.Colors.Light.primaryBgIdle
 *   IconButtonTokens.Sizing.Compact.height
 *   IconButtonTokens.Density.Default.contentGap
 */
object IconButtonTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = IconButtonTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val iconButtonBorderRadius: Dp
        }

        object Compact : SizingTokens {
            override val iconButtonBorderRadius = 8.dp
        }
        object Medium : SizingTokens {
            override val iconButtonBorderRadius = 8.dp
        }
        object Expanded : SizingTokens {
            override val iconButtonBorderRadius = 8.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // DENSITY (WindowSizeClass × Density Matrix)
    // ══════════════════════════════════════════════════════════════
    object Density {
        /**
         * Returns density tokens resolved by WindowSizeClass × DensityMode.
         * Values are pre-resolved from the Breakpoint × Density matrix at build-time.
         *
         * Usage:
         *   val gap = IconButtonTokens.Density.current().iconButtonSize
         */
        @Composable
        fun current(): DensityTokens {
            val sizeClass = DesignSystemTheme.sizeClass
            val density = DesignSystemTheme.density
            return when (sizeClass) {
                WindowSizeClass.Compact -> when (density) {
                    com.bild.designsystem.shared.Density.Dense -> CompactDense
                    com.bild.designsystem.shared.Density.Default -> CompactDefault
                    com.bild.designsystem.shared.Density.Spacious -> CompactSpacious
                }
                WindowSizeClass.Medium -> when (density) {
                    com.bild.designsystem.shared.Density.Dense -> MediumDense
                    com.bild.designsystem.shared.Density.Default -> MediumDefault
                    com.bild.designsystem.shared.Density.Spacious -> MediumSpacious
                }
                WindowSizeClass.Expanded -> when (density) {
                    com.bild.designsystem.shared.Density.Dense -> ExpandedDense
                    com.bild.designsystem.shared.Density.Default -> ExpandedDefault
                    com.bild.designsystem.shared.Density.Spacious -> ExpandedSpacious
                }
            }
        }

        /**
         * Interface for density tokens (WindowSizeClass × Density resolved)
         */
        interface DensityTokens {
            val iconButtonSize: Dp
        }

        object CompactDense : DensityTokens {
            override val iconButtonSize = 40.dp
        }
        object CompactDefault : DensityTokens {
            override val iconButtonSize = 48.dp
        }
        object CompactSpacious : DensityTokens {
            override val iconButtonSize = 56.dp
        }
        object MediumDense : DensityTokens {
            override val iconButtonSize = 40.dp
        }
        object MediumDefault : DensityTokens {
            override val iconButtonSize = 48.dp
        }
        object MediumSpacious : DensityTokens {
            override val iconButtonSize = 56.dp
        }
        object ExpandedDense : DensityTokens {
            override val iconButtonSize = 40.dp
        }
        object ExpandedDefault : DensityTokens {
            override val iconButtonSize = 48.dp
        }
        object ExpandedSpacious : DensityTokens {
            override val iconButtonSize = 56.dp
        }
    }
}
