// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.0.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Empties
Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/vv-token-test-v3/blob/main/packages/tokens/docs/ios.md

import SwiftUI

/// Empties Design Tokens
///
/// Usage:
///   EmptiesTokens.Colors.light.primaryBgIdle
///   EmptiesTokens.Sizing.compact.height
///   EmptiesTokens.Density.current(for: theme.density).contentGap
public enum EmptiesTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol EmptiesColorTokens: Sendable {
        var emptiesBgColor: Color { get }
        var emptiesLogoColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any EmptiesColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: EmptiesColorTokens {
            public static let shared = Light()
            private init() {}
            public let emptiesBgColor: Color = Color(hex: 0xEFF1F5)
            public let emptiesLogoColor: Color = Color(hex: 0xC3C9DB)
        }

        public struct Dark: EmptiesColorTokens {
            public static let shared = Dark()
            private init() {}
            public let emptiesBgColor: Color = Color(hex: 0x113B72)
            public let emptiesLogoColor: Color = Color(hex: 0x0C2F61)
        }
    }
}
