// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.1
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Table
// Aggregated component tokens with all modes
//
// Brand: Bild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Bild Table Design Tokens
///
/// Usage:
///   BildTableTokens.Colors.light.primaryBgIdle
///   BildTableTokens.Sizing.compact.height
///   BildTableTokens.Density.current(for: theme.density).contentGap
public enum BildTableTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol BildTableSizingTokens: Sendable {
        var tableColumnWidthSize1x: CGFloat { get }
        var tableColumnWidthSize2x: CGFloat { get }
        var tableColumnWidthSize0p5x: CGFloat { get }
        var tableColumnWidthSize1p5x: CGFloat { get }
        var tableColumnWidthSize2p5x: CGFloat { get }
        var tableColumnWidthSize0p75x: CGFloat { get }
        var tableColumnWidthSize3x: CGFloat { get }
        var tableItemMaxWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any BildTableSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: BildTableSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let tableColumnWidthSize1x: CGFloat = 80
            public let tableColumnWidthSize2x: CGFloat = 140
            public let tableColumnWidthSize0p5x: CGFloat = 40
            public let tableColumnWidthSize1p5x: CGFloat = 120
            public let tableColumnWidthSize2p5x: CGFloat = 180
            public let tableColumnWidthSize0p75x: CGFloat = 56
            public let tableColumnWidthSize3x: CGFloat = 200
            public let tableItemMaxWidthSize: CGFloat = 224
        }

        public struct Regular: BildTableSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let tableColumnWidthSize1x: CGFloat = 140
            public let tableColumnWidthSize2x: CGFloat = 220
            public let tableColumnWidthSize0p5x: CGFloat = 72
            public let tableColumnWidthSize1p5x: CGFloat = 180
            public let tableColumnWidthSize2p5x: CGFloat = 240
            public let tableColumnWidthSize0p75x: CGFloat = 100
            public let tableColumnWidthSize3x: CGFloat = 280
            public let tableItemMaxWidthSize: CGFloat = 224
        }
    }
}
