/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.4.3
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Iconbutton
 * Aggregated component tokens with all modes
 *
 * Brand: Advertorial
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.advertorial.components.iconbutton

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Iconbutton Design Tokens
 *
 * Usage:
 *   IconbuttonTokens.Colors.Light.primaryBgIdle
 *   IconbuttonTokens.Sizing.Compact.height
 *   IconbuttonTokens.Density.Default.contentGap
 */
object IconbuttonTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = IconbuttonTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val iconButtonSize: Dp
            val iconButtonBorderRadius: Dp
        }

        object Compact : SizingTokens {
            override val iconButtonSize = 40.dp
            override val iconButtonBorderRadius = 8.dp
        }
        object Medium : SizingTokens {
            override val iconButtonSize = 40.dp
            override val iconButtonBorderRadius = 8.dp
        }
        object Expanded : SizingTokens {
            override val iconButtonSize = 40.dp
            override val iconButtonBorderRadius = 8.dp
        }
    }
}
