// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.2
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Card
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Card Design Tokens
///
/// Usage:
///   SportbildCardTokens.Colors.light.primaryBgIdle
///   SportbildCardTokens.Sizing.compact.height
///   SportbildCardTokens.Density.current(for: theme.density).contentGap
public enum SportbildCardTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SportbildCardColorTokens: Sendable {
        var cardSurfaceBgColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildCardColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildCardColorTokens {
            public static let shared = Light()
            private init() {}
            public let cardSurfaceBgColor: Color = Color(hex: 0xFFFFFF)
        }

        public struct Dark: SportbildCardColorTokens {
            public static let shared = Dark()
            private init() {}
            public let cardSurfaceBgColor: Color = Color(hex: 0x0C2F61)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildCardSizingTokens: Sendable {
        var searchResultCardImageWidthSize: CGFloat { get }
        var searchResultCardImageHeightSizeStacked: CGFloat { get }
        var newstickerImageCardWidthSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildCardSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildCardSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let searchResultCardImageWidthSize: CGFloat = 216
            public let searchResultCardImageHeightSizeStacked: CGFloat = 189
            public let newstickerImageCardWidthSize: CGFloat = 206
        }

        public struct Regular: SportbildCardSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let searchResultCardImageWidthSize: CGFloat = 260
            public let searchResultCardImageHeightSizeStacked: CGFloat = 189
            public let newstickerImageCardWidthSize: CGFloat = 206
        }
    }
}
