// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.3
// Generated by Style Dictionary v5.1.4
//
// Context: Component: InputField
// Aggregated component tokens with all modes
//
// Brand: Advertorial
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Advertorial InputField Design Tokens
///
/// Usage:
///   AdvertorialInputFieldTokens.Colors.light.primaryBgIdle
///   AdvertorialInputFieldTokens.Sizing.compact.height
///   AdvertorialInputFieldTokens.Density.current(for: theme.density).contentGap
public enum AdvertorialInputFieldTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol AdvertorialInputFieldSizingTokens: Sendable {
        var inputFieldMiniLabelInlineSpace: CGFloat { get }
        var inputFieldImessageInlineSpace: CGFloat { get }
        var heyInputContainerInlineSpace: CGFloat { get }
        var inputFieldMessageGapSpace: CGFloat { get }
        var inputFieldLabelFontFamily: String { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialInputFieldSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialInputFieldSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let inputFieldMiniLabelInlineSpace: CGFloat = 4
            public let inputFieldImessageInlineSpace: CGFloat = 16
            public let heyInputContainerInlineSpace: CGFloat = 8
            public let inputFieldMessageGapSpace: CGFloat = 4
            public let inputFieldLabelFontFamily: String = "Lucida Grande"
        }

        public struct Regular: AdvertorialInputFieldSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let inputFieldMiniLabelInlineSpace: CGFloat = 4
            public let inputFieldImessageInlineSpace: CGFloat = 16
            public let heyInputContainerInlineSpace: CGFloat = 16
            public let inputFieldMessageGapSpace: CGFloat = 4
            public let inputFieldLabelFontFamily: String = "Lucida Grande"
        }
    }

    // MARK: - Density (SizeClass × Density Matrix)

    /// Density tokens protocol (SizeClass × Density resolved)
    public protocol AdvertorialInputFieldDensityTokens: Sendable {
        var inputFieldStackSpace: CGFloat { get }
        var inputFieldInlineSpace: CGFloat { get }
        var inputFieldLabelFontSize: CGFloat { get }
        var inputFieldHeightSize: CGFloat { get }
        var inputFieldLabelLineHeight: CGFloat { get }
    }

    /// Density accessor with SizeClass × Density resolution
    public enum DensityAccessor {
        /// Returns density tokens resolved by SizeClass × DensityMode
        public static func current(for sizeClass: SizeClass, density: Density) -> any AdvertorialInputFieldDensityTokens {
            switch (sizeClass, density) {
            case (.compact, .dense): return CompactDense.shared
            case (.compact, .default): return CompactDefault.shared
            case (.compact, .spacious): return CompactSpacious.shared
            case (.regular, .dense): return RegularDense.shared
            case (.regular, .default): return RegularDefault.shared
            case (.regular, .spacious): return RegularSpacious.shared
            }
        }

        public struct CompactDense: AdvertorialInputFieldDensityTokens {
            public static let shared = CompactDense()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 6
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 16
            public let inputFieldHeightSize: CGFloat = 36
            public let inputFieldLabelLineHeight: CGFloat = 16
        }

        public struct CompactDefault: AdvertorialInputFieldDensityTokens {
            public static let shared = CompactDefault()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 8
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 17
            public let inputFieldHeightSize: CGFloat = 40
            public let inputFieldLabelLineHeight: CGFloat = 17
        }

        public struct CompactSpacious: AdvertorialInputFieldDensityTokens {
            public static let shared = CompactSpacious()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 12
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 19
            public let inputFieldHeightSize: CGFloat = 48
            public let inputFieldLabelLineHeight: CGFloat = 19
        }

        public struct RegularDense: AdvertorialInputFieldDensityTokens {
            public static let shared = RegularDense()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 6
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 16
            public let inputFieldHeightSize: CGFloat = 36
            public let inputFieldLabelLineHeight: CGFloat = 16
        }

        public struct RegularDefault: AdvertorialInputFieldDensityTokens {
            public static let shared = RegularDefault()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 8
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 17
            public let inputFieldHeightSize: CGFloat = 40
            public let inputFieldLabelLineHeight: CGFloat = 17
        }

        public struct RegularSpacious: AdvertorialInputFieldDensityTokens {
            public static let shared = RegularSpacious()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 12
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 19
            public let inputFieldHeightSize: CGFloat = 48
            public let inputFieldLabelLineHeight: CGFloat = 19
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol AdvertorialInputFieldTypographyTokens: Sendable {
        var inputFieldLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any AdvertorialInputFieldTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: AdvertorialInputFieldTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let inputFieldLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: AdvertorialInputFieldTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let inputFieldLabel: TextStyle = TextStyle( fontFamily: "Lucida Grande", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
