// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.5.0
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Inputfield
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Inputfield Design Tokens
///
/// Usage:
///   SportbildInputfieldTokens.Colors.light.primaryBgIdle
///   SportbildInputfieldTokens.Sizing.compact.height
///   SportbildInputfieldTokens.Density.current(for: theme.density).contentGap
public enum SportbildInputfieldTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SportbildInputfieldColorTokens: Sendable {
        var inputFieldBorderColorIdle: Color { get }
        var inputFieldBorderColorActive: Color { get }
        var inputFieldBorderColorDisabled: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildInputfieldColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildInputfieldColorTokens {
            public static let shared = Light()
            private init() {}
            public let inputFieldBorderColorIdle: Color = Color(hex: 0x6A91CF)
            public let inputFieldBorderColorActive: Color = Color(hex: 0x174482)
            public let inputFieldBorderColorDisabled: Color = Color(hex: 0xD6E1F2)
        }

        public struct Dark: SportbildInputfieldColorTokens {
            public static let shared = Dark()
            private init() {}
            public let inputFieldBorderColorIdle: Color = Color(hex: 0x4676C3)
            public let inputFieldBorderColorActive: Color = Color(hex: 0x8FACDB)
            public let inputFieldBorderColorDisabled: Color = Color(hex: 0x113B72)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildInputfieldSizingTokens: Sendable {
        var inputFieldMiniLabelInlineSpace: CGFloat { get }
        var inputFieldImessageInlineSpace: CGFloat { get }
        var heyInputContainerInlineSpace: CGFloat { get }
        var inputFieldMessageGapSpace: CGFloat { get }
        var inputFieldLabelFontFamily: String { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildInputfieldSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildInputfieldSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let inputFieldMiniLabelInlineSpace: CGFloat = 4
            public let inputFieldImessageInlineSpace: CGFloat = 16
            public let heyInputContainerInlineSpace: CGFloat = 8
            public let inputFieldMessageGapSpace: CGFloat = 4
            public let inputFieldLabelFontFamily: String = "Inter"
        }

        public struct Regular: SportbildInputfieldSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let inputFieldMiniLabelInlineSpace: CGFloat = 4
            public let inputFieldImessageInlineSpace: CGFloat = 16
            public let heyInputContainerInlineSpace: CGFloat = 16
            public let inputFieldMessageGapSpace: CGFloat = 4
            public let inputFieldLabelFontFamily: String = "Inter"
        }
    }

    // MARK: - Density (SizeClass × Density Matrix)

    /// Density tokens protocol (SizeClass × Density resolved)
    public protocol SportbildInputfieldDensityTokens: Sendable {
        var inputFieldStackSpace: CGFloat { get }
        var inputFieldInlineSpace: CGFloat { get }
        var inputFieldLabelFontSize: CGFloat { get }
        var inputFieldHeightSize: CGFloat { get }
        var inputFieldLabelLineHeight: CGFloat { get }
    }

    /// Density accessor with SizeClass × Density resolution
    public enum DensityAccessor {
        /// Returns density tokens resolved by SizeClass × DensityMode
        public static func current(for sizeClass: SizeClass, density: Density) -> any SportbildInputfieldDensityTokens {
            switch (sizeClass, density) {
            case (.compact, .dense): return CompactDense.shared
            case (.compact, .default): return CompactDefault.shared
            case (.compact, .spacious): return CompactSpacious.shared
            case (.regular, .dense): return RegularDense.shared
            case (.regular, .default): return RegularDefault.shared
            case (.regular, .spacious): return RegularSpacious.shared
            }
        }

        public struct CompactDense: SportbildInputfieldDensityTokens {
            public static let shared = CompactDense()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 6
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 16
            public let inputFieldHeightSize: CGFloat = 36
            public let inputFieldLabelLineHeight: CGFloat = 16
        }

        public struct CompactDefault: SportbildInputfieldDensityTokens {
            public static let shared = CompactDefault()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 8
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 17
            public let inputFieldHeightSize: CGFloat = 40
            public let inputFieldLabelLineHeight: CGFloat = 17
        }

        public struct CompactSpacious: SportbildInputfieldDensityTokens {
            public static let shared = CompactSpacious()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 12
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 19
            public let inputFieldHeightSize: CGFloat = 48
            public let inputFieldLabelLineHeight: CGFloat = 19
        }

        public struct RegularDense: SportbildInputfieldDensityTokens {
            public static let shared = RegularDense()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 6
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 16
            public let inputFieldHeightSize: CGFloat = 36
            public let inputFieldLabelLineHeight: CGFloat = 16
        }

        public struct RegularDefault: SportbildInputfieldDensityTokens {
            public static let shared = RegularDefault()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 8
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 17
            public let inputFieldHeightSize: CGFloat = 40
            public let inputFieldLabelLineHeight: CGFloat = 17
        }

        public struct RegularSpacious: SportbildInputfieldDensityTokens {
            public static let shared = RegularSpacious()
            private init() {}
            public let inputFieldStackSpace: CGFloat = 12
            public let inputFieldInlineSpace: CGFloat = 16
            public let inputFieldLabelFontSize: CGFloat = 19
            public let inputFieldHeightSize: CGFloat = 48
            public let inputFieldLabelLineHeight: CGFloat = 19
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol SportbildInputfieldTypographyTokens: Sendable {
        var inputFieldLabel: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildInputfieldTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildInputfieldTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let inputFieldLabel: TextStyle = TextStyle( fontFamily: "Inter", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: SportbildInputfieldTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let inputFieldLabel: TextStyle = TextStyle( fontFamily: "Inter", fontWeight: .regular, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }
}
