// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.3.23
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Skeletons
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Skeletons Design Tokens
///
/// Usage:
///   SportbildSkeletonsTokens.Colors.light.primaryBgIdle
///   SportbildSkeletonsTokens.Sizing.compact.height
///   SportbildSkeletonsTokens.Density.current(for: theme.density).contentGap
public enum SportbildSkeletonsTokens {

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildSkeletonsSizingTokens: Sendable {
        var headlinesSkeletonImagePlaceholderMaxWidth: CGFloat { get }
        var articleSkeletonImageInlineSpace: CGFloat { get }
        var articleSkeletonTextInlineSpace: CGFloat { get }
        var articleTextSkeletonHeightSize: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildSkeletonsSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildSkeletonsSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let headlinesSkeletonImagePlaceholderMaxWidth: CGFloat = 282
            public let articleSkeletonImageInlineSpace: CGFloat = 12
            public let articleSkeletonTextInlineSpace: CGFloat = 0
            public let articleTextSkeletonHeightSize: CGFloat = 270
        }

        public struct Regular: SportbildSkeletonsSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let headlinesSkeletonImagePlaceholderMaxWidth: CGFloat = 160
            public let articleSkeletonImageInlineSpace: CGFloat = 48
            public let articleSkeletonTextInlineSpace: CGFloat = 48
            public let articleTextSkeletonHeightSize: CGFloat = 720
        }
    }
}
