// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.3
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Subheader
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Subheader Design Tokens
///
/// Usage:
///   SportbildSubheaderTokens.Colors.light.primaryBgIdle
///   SportbildSubheaderTokens.Sizing.compact.height
///   SportbildSubheaderTokens.Density.current(for: theme.density).contentGap
public enum SportbildSubheaderTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SportbildSubheaderColorTokens: Sendable {
        var subheadersTextColor: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildSubheaderColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildSubheaderColorTokens {
            public static let shared = Light()
            private init() {}
            public let subheadersTextColor: Color = Color(hex: 0x222628)
        }

        public struct Dark: SportbildSubheaderColorTokens {
            public static let shared = Dark()
            private init() {}
            public let subheadersTextColor: Color = Color(hex: 0xD6E1F2)
        }
    }
}
