/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.8.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Specialnavi
 * Aggregated component tokens with all modes
 *
 * Brand: Sportbild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.sportbild.components.specialnavi

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * Specialnavi Design Tokens
 *
 * Usage:
 *   SpecialnaviTokens.Colors.Light.primaryBgIdle
 *   SpecialnaviTokens.Sizing.Compact.height
 *   SpecialnaviTokens.Density.Default.contentGap
 */
object SpecialnaviTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = SpecialnaviTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val specialNaviInlineSpace: Dp
        }

        object Compact : SizingTokens {
            override val specialNaviInlineSpace = 24.dp
        }
        object Medium : SizingTokens {
            override val specialNaviInlineSpace = 24.dp
        }
        object Expanded : SizingTokens {
            override val specialNaviInlineSpace = 32.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = SpecialnaviTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val SpecialNaviItemLabel: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val SpecialNaviItemLabel = DesignTextStyle(fontFamily = "AntennaExtraCond", fontWeight = FontWeight.Bold, fontSize = 18.sp, lineHeight = 18.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val SpecialNaviItemLabel = DesignTextStyle(fontFamily = "AntennaExtraCond", fontWeight = FontWeight.Bold, fontSize = 18.sp, lineHeight = 18.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val SpecialNaviItemLabel = DesignTextStyle(fontFamily = "AntennaExtraCond", fontWeight = FontWeight.Bold, fontSize = 18.sp, lineHeight = 18.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
    }
}
