/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.5.0
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: Sectiontitle
 * Aggregated component tokens with all modes
 *
 * Brand: Bild
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-android/docs/USAGE.md
 */

package com.bild.designsystem.brands.bild.components.sectiontitle

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp

/**
 * Sectiontitle Design Tokens
 *
 * Usage:
 *   SectiontitleTokens.Colors.Light.primaryBgIdle
 *   SectiontitleTokens.Sizing.Compact.height
 *   SectiontitleTokens.Density.Default.contentGap
 */
object SectiontitleTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = SectiontitleTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val sectionTitleInnerStackBottomSpace: Dp
            val sectionTitleHeightSize: Dp
            val sectionTitleArrowInlineSpace: Dp
            val sectionTitleArrowInlineSpaceActive: Dp
        }

        object Compact : SizingTokens {
            override val sectionTitleInnerStackBottomSpace = 12.dp
            override val sectionTitleHeightSize = 32.dp
            override val sectionTitleArrowInlineSpace = 5.dp
            override val sectionTitleArrowInlineSpaceActive = 5.dp
        }
        object Medium : SizingTokens {
            override val sectionTitleInnerStackBottomSpace = 12.dp
            override val sectionTitleHeightSize = 32.dp
            override val sectionTitleArrowInlineSpace = 5.dp
            override val sectionTitleArrowInlineSpaceActive = 5.dp
        }
        object Expanded : SizingTokens {
            override val sectionTitleInnerStackBottomSpace = 12.dp
            override val sectionTitleHeightSize = 40.dp
            override val sectionTitleArrowInlineSpace = 5.dp
            override val sectionTitleArrowInlineSpaceActive = 8.dp
        }
    }
}
