// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.7.1
// Generated by Style Dictionary v5.1.4
//
// Brand: Bild | Context: Typography regular
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/ios.md
import SwiftUI

/// Regular typography implementation
public struct BildTypographyRegular: BildTypographyScheme, DesignTypographyScheme {
    public static let shared = BildTypographyRegular()
    private init() {}

    public let display1 = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .black,
        fontSize: 120,
        lineHeight: 120,
        letterSpacing: -2,
        textCase: .original,
        textDecoration: .none
    )
    public let display2 = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .black,
        fontSize: 64,
        lineHeight: 64,
        letterSpacing: -1,
        textCase: .original,
        textDecoration: .none
    )
    public let display3 = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .black,
        fontSize: 40,
        lineHeight: 40,
        letterSpacing: -1,
        textCase: .original,
        textDecoration: .none
    )
    public let headline1 = TextStyle(
        fontFamily: "Gotham Condensed",
        fontWeight: .black,
        fontSize: 100,
        lineHeight: 100,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let headline2 = TextStyle(
        fontFamily: "Gotham Condensed",
        fontWeight: .black,
        fontSize: 64,
        lineHeight: 64,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let headline3 = TextStyle(
        fontFamily: "Gotham Condensed",
        fontWeight: .black,
        fontSize: 40,
        lineHeight: 40,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let headline4 = TextStyle(
        fontFamily: "Gotham Condensed",
        fontWeight: .bold,
        fontSize: 32,
        lineHeight: 30,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let subheadline1 = TextStyle(
        fontFamily: "Gotham Condensed",
        fontWeight: .bold,
        fontSize: 36,
        lineHeight: 36,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let kicker1 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 30,
        lineHeight: 30,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let kicker2 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 24,
        lineHeight: 24,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let kicker3 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 20,
        lineHeight: 20,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let kicker4 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 16,
        lineHeight: 16,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let title1 = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 28,
        lineHeight: 28,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let title1uppercase = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 28,
        lineHeight: 28,
        letterSpacing: 0,
        textCase: .upper,
        textDecoration: .none
    )
    public let title2 = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 20,
        lineHeight: 22,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let title2uppercase = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 20,
        lineHeight: 22,
        letterSpacing: 0,
        textCase: .upper,
        textDecoration: .none
    )
    public let callout = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 22,
        lineHeight: 22,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let body = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let bodyItalic = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let bodyBold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let bodyBoldItalic = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let textLink = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .underline
    )
    public let textLinkItalic = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .underline
    )
    public let textLinkBold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .underline
    )
    public let textLinkHover = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .underline
    )
    public let textLinkBoldHover = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 21,
        lineHeight: 32,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .underline
    )
    public let footnote1 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 18,
        lineHeight: 23,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let footnote1bold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 18,
        lineHeight: 23,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let footnote2 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let footnote2bold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let label1 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 17,
        lineHeight: 17,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label1bold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 17,
        lineHeight: 17,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label1uppercaseBold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 17,
        lineHeight: 17,
        letterSpacing: 0.5,
        textCase: .upper,
        textDecoration: .none
    )
    public let label2 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 15,
        lineHeight: 16,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label2uppercase = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 15,
        lineHeight: 16,
        letterSpacing: 0.25,
        textCase: .upper,
        textDecoration: .none
    )
    public let label2bold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 15,
        lineHeight: 16,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label2uppercaseBold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 15,
        lineHeight: 16,
        letterSpacing: 0.25,
        textCase: .upper,
        textDecoration: .none
    )
    public let label3 = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 12,
        lineHeight: 14.4,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label3uppercase = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 12,
        lineHeight: 14.4,
        letterSpacing: 0.5,
        textCase: .upper,
        textDecoration: .none
    )
    public let label3bold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 12,
        lineHeight: 14.4,
        letterSpacing: 0.25,
        textCase: .original,
        textDecoration: .none
    )
    public let label3uppercaseBold = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .bold,
        fontSize: 12,
        lineHeight: 14.4,
        letterSpacing: 0.5,
        textCase: .upper,
        textDecoration: .none
    )
    public let quote = TextStyle(
        fontFamily: "Gotham",
        fontWeight: .heavy,
        fontSize: 20,
        lineHeight: 22,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
    public let testStyle = TextStyle(
        fontFamily: "Gotham XNarrow",
        fontWeight: .regular,
        fontSize: 21,
        lineHeight: 1.2,
        letterSpacing: 0,
        textCase: .original,
        textDecoration: .none
    )
}
