/**
 * Do not edit directly, this file was auto-generated.
 *
 * BILD Design System Tokens v1.3.11
 * Generated by Style Dictionary v5.1.4
 *
 * Context: Component: LiveTicker
 * Aggregated component tokens with all modes
 *
 * Brand: Advertorial
 *
 * Copyright (c) 2026 Axel Springer Deutschland GmbH
 * Proprietary and confidential. All rights reserved.
 *
 * Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens/docs/android.md
 */

package com.bild.designsystem.advertorial.components

import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Composable
import com.bild.designsystem.shared.DesignSystemTheme
import com.bild.designsystem.shared.WindowSizeClass
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.ui.unit.TextUnit
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextDecoration
import com.bild.designsystem.shared.DesignTextStyle
import com.bild.designsystem.shared.DesignTextCase

/**
 * LiveTicker Design Tokens
 *
 * Usage:
 *   LiveTickerTokens.Colors.Light.primaryBgIdle
 *   LiveTickerTokens.Sizing.Compact.height
 *   LiveTickerTokens.Density.Default.contentGap
 */
object LiveTickerTokens {

    // ══════════════════════════════════════════════════════════════
    // SIZING (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Sizing {
        /**
         * Returns sizing tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontSize = LiveTickerTokens.Sizing.current().labelFontSize
         */
        @Composable
        fun current(): SizingTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for sizing tokens
         */
        interface SizingTokens {
            val liveTickerheadlineFontWeight: Int
            val liveTickerHeadlinesFontSize: TextUnit
            val timeStampFontFamily: Dp
            val liveTickerTimeStampFontSize: TextUnit
            val liveTickerTimeHeadlineStackSpace: Dp
            val liveTickerSliderItemWidthMaxSize: Dp
            val liveTickerAppCardHeightSize: Dp
            val liveTickerAppCardWidthSize: Dp
        }

        object Compact : SizingTokens {
            override val liveTickerheadlineFontWeight = 600
            override val liveTickerHeadlinesFontSize = 22.sp
            override val timeStampFontFamily = "Gotham XNarrow"
            override val liveTickerTimeStampFontSize = 14.sp
            override val liveTickerTimeHeadlineStackSpace = 4.dp
            override val liveTickerSliderItemWidthMaxSize = 257.dp
            override val liveTickerAppCardHeightSize = 96.dp
            override val liveTickerAppCardWidthSize = 250.dp
        }
        object Medium : SizingTokens {
            override val liveTickerheadlineFontWeight = 600
            override val liveTickerHeadlinesFontSize = 32.sp
            override val timeStampFontFamily = "Gotham XNarrow"
            override val liveTickerTimeStampFontSize = 16.sp
            override val liveTickerTimeHeadlineStackSpace = 4.dp
            override val liveTickerSliderItemWidthMaxSize = 257.dp
            override val liveTickerAppCardHeightSize = 128.dp
            override val liveTickerAppCardWidthSize = 300.dp
        }
        object Expanded : SizingTokens {
            override val liveTickerheadlineFontWeight = 600
            override val liveTickerHeadlinesFontSize = 32.sp
            override val timeStampFontFamily = "Gotham XNarrow"
            override val liveTickerTimeStampFontSize = 16.sp
            override val liveTickerTimeHeadlineStackSpace = 4.dp
            override val liveTickerSliderItemWidthMaxSize = 537.dp
            override val liveTickerAppCardHeightSize = 128.dp
            override val liveTickerAppCardWidthSize = 300.dp
        }
    }

    // ══════════════════════════════════════════════════════════════
    // TYPOGRAPHY (Material 3 WindowSizeClass)
    // ══════════════════════════════════════════════════════════════
    object Typography {
        /**
         * Returns typography tokens for the current window size class.
         * Automatically resolves to Compact, Medium, or Expanded based on DesignSystemTheme.sizeClass
         *
         * Usage:
         *   val fontFamily = LiveTickerTokens.Typography.current().labelFontFamily
         */
        @Composable
        fun current(): TypographyTokens = when (DesignSystemTheme.sizeClass) {
            WindowSizeClass.Compact -> Compact
            WindowSizeClass.Medium -> Medium
            WindowSizeClass.Expanded -> Expanded
        }

        /**
         * Interface for typography tokens (DesignTextStyle composite objects)
         */
        interface TypographyTokens {
            val liveTickerHeadline: DesignTextStyle
            val liveTickerTimeStamp: DesignTextStyle
        }

        object Compact : TypographyTokens {
            override val liveTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.SemiBold, fontSize = 22.sp, lineHeight = 22.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val liveTickerTimeStamp = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 14.sp, lineHeight = 14.sp, letterSpacing = 0.sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Medium : TypographyTokens {
            override val liveTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.SemiBold, fontSize = 32.sp, lineHeight = 32.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val liveTickerTimeStamp = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 16.sp, letterSpacing = 0.sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
        object Expanded : TypographyTokens {
            override val liveTickerHeadline = DesignTextStyle(fontFamily = "Lucida Grande", fontWeight = FontWeight.SemiBold, fontSize = 32.sp, lineHeight = 32.sp, letterSpacing = (0).sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
            override val liveTickerTimeStamp = DesignTextStyle(fontFamily = "Gotham XNarrow", fontWeight = FontWeight.Bold, fontSize = 16.sp, lineHeight = 16.sp, letterSpacing = 0.sp, textCase = DesignTextCase.Original, textDecoration = TextDecoration.None)
        }
    }
}
