// Do not edit directly, this file was auto-generated.
//
// BILD Design System Tokens v1.4.3
// Generated by Style Dictionary v5.1.4
//
// Context: Component: Teaser
// Aggregated component tokens with all modes
//
// Brand: Sportbild
//
// Copyright (c) 2026 Axel Springer Deutschland GmbH
// Proprietary and confidential. All rights reserved.
//
// Documentation: https://github.com/UXWizard25/bild-design-system/blob/main/packages/tokens-ios/Documentation/USAGE.md

import SwiftUI

/// Sportbild Teaser Design Tokens
///
/// Usage:
///   SportbildTeaserTokens.Colors.light.primaryBgIdle
///   SportbildTeaserTokens.Sizing.compact.height
///   SportbildTeaserTokens.Density.current(for: theme.density).contentGap
public enum SportbildTeaserTokens {

    // MARK: - Colors

    /// Color tokens protocol
    public protocol SportbildTeaserColorTokens: Sendable {
        var teaserHoverOpacity: CGFloat { get }
        var teaserTitleBgGradientStart: Color { get }
        var teaserTitleBgGradientStop: Color { get }
    }

    /// Color scheme accessor
    public enum Colors {
        /// Returns color tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildTeaserColorTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildTeaserColorTokens {
            public static let shared = Light()
            private init() {}
            public let teaserHoverOpacity: CGFloat = 0.8
            public let teaserTitleBgGradientStart: Color = Color(hex: 0x0B2647, alpha: 0.70)
            public let teaserTitleBgGradientStop: Color = Color(hex: 0x0B2647, alpha: 0.00)
        }

        public struct Dark: SportbildTeaserColorTokens {
            public static let shared = Dark()
            private init() {}
            public let teaserHoverOpacity: CGFloat = 0.8
            public let teaserTitleBgGradientStart: Color = Color(hex: 0x0B2647, alpha: 0.70)
            public let teaserTitleBgGradientStop: Color = Color(hex: 0x0B2647, alpha: 0.00)
        }
    }

    // MARK: - Sizing

    /// Sizing tokens protocol
    public protocol SportbildTeaserSizingTokens: Sendable {
        var teaserTitleInlineLeftSpace: CGFloat { get }
        var teaserTitleStackSpace: CGFloat { get }
        var mQteaserHeadlineFontSize: CGFloat { get }
        var mQteaserHeadlineLineHeight: CGFloat { get }
        var mqTeaserTitleInlineSpace: CGFloat { get }
        var aTeaserKickerFontSize: CGFloat { get }
        var aTeaserHeadlineFontSize: CGFloat { get }
        var aTeaserKickerLineHeight: CGFloat { get }
        var aTeaserHeadlineLineHeight: CGFloat { get }
        var aTeaserTitleInlineSpace: CGFloat { get }
        var teaserTitleGapSpace: CGFloat { get }
        var stdTeaserImageTitleGapSpace: CGFloat { get }
        var stdTeaserBadgesMarginSpace: CGFloat { get }
        var stdTeaserKickerHeadlineStackSpace: CGFloat { get }
        var teaserKickerBgInlineSpace: CGFloat { get }
        var teaserKickerBgStackSpace: CGFloat { get }
        var quadHeadlineFontSize: CGFloat { get }
        var quadKickerFontSize: CGFloat { get }
        var quadHeadlineLineHeight: CGFloat { get }
        var qTeaserTitleInlineSpace: CGFloat { get }
        var teaserBadgesMarginSpace: CGFloat { get }
        var teaserBadgesHeightSizeLg: CGFloat { get }
        var teaserTitleBottomStackSpace: CGFloat { get }
        var teaserBadgesHeightSizeSm: CGFloat { get }
        var bildPlayTeaserWidthSize: CGFloat { get }
        var teaserLayoutGridSpace: CGFloat { get }
        var superAteaserTitleInlineSpace: CGFloat { get }
        var bTeaserTitleInlineSpace: CGFloat { get }
    }

    /// Size class accessor
    public enum Sizing {
        /// Returns sizing tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildTeaserSizingTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildTeaserSizingTokens {
            public static let shared = Compact()
            private init() {}
            public let teaserTitleInlineLeftSpace: CGFloat = 12
            public let teaserTitleStackSpace: CGFloat = 4
            public let mQteaserHeadlineFontSize: CGFloat = 21
            public let mQteaserHeadlineLineHeight: CGFloat = 23.1
            public let mqTeaserTitleInlineSpace: CGFloat = 12
            public let aTeaserKickerFontSize: CGFloat = 16
            public let aTeaserHeadlineFontSize: CGFloat = 30
            public let aTeaserKickerLineHeight: CGFloat = 16
            public let aTeaserHeadlineLineHeight: CGFloat = 30
            public let aTeaserTitleInlineSpace: CGFloat = 12
            public let teaserTitleGapSpace: CGFloat = 4
            public let stdTeaserImageTitleGapSpace: CGFloat = 4
            public let stdTeaserBadgesMarginSpace: CGFloat = 4
            public let stdTeaserKickerHeadlineStackSpace: CGFloat = 2
            public let teaserKickerBgInlineSpace: CGFloat = 6
            public let teaserKickerBgStackSpace: CGFloat = 2
            public let quadHeadlineFontSize: CGFloat = 42
            public let quadKickerFontSize: CGFloat = 20
            public let quadHeadlineLineHeight: CGFloat = 42
            public let qTeaserTitleInlineSpace: CGFloat = 12
            public let teaserBadgesMarginSpace: CGFloat = 8
            public let teaserBadgesHeightSizeLg: CGFloat = 32
            public let teaserTitleBottomStackSpace: CGFloat = 12
            public let teaserBadgesHeightSizeSm: CGFloat = 24
            public let bildPlayTeaserWidthSize: CGFloat = 145
            public let teaserLayoutGridSpace: CGFloat = 12
            public let superAteaserTitleInlineSpace: CGFloat = 24
            public let bTeaserTitleInlineSpace: CGFloat = 16
        }

        public struct Regular: SportbildTeaserSizingTokens {
            public static let shared = Regular()
            private init() {}
            public let teaserTitleInlineLeftSpace: CGFloat = 0
            public let teaserTitleStackSpace: CGFloat = 6
            public let mQteaserHeadlineFontSize: CGFloat = 34
            public let mQteaserHeadlineLineHeight: CGFloat = 39.1
            public let mqTeaserTitleInlineSpace: CGFloat = 12
            public let aTeaserKickerFontSize: CGFloat = 26
            public let aTeaserHeadlineFontSize: CGFloat = 50
            public let aTeaserKickerLineHeight: CGFloat = 26
            public let aTeaserHeadlineLineHeight: CGFloat = 57.6
            public let aTeaserTitleInlineSpace: CGFloat = 16
            public let teaserTitleGapSpace: CGFloat = 4
            public let stdTeaserImageTitleGapSpace: CGFloat = 6
            public let stdTeaserBadgesMarginSpace: CGFloat = 8
            public let stdTeaserKickerHeadlineStackSpace: CGFloat = 2
            public let teaserKickerBgInlineSpace: CGFloat = 6
            public let teaserKickerBgStackSpace: CGFloat = 2
            public let quadHeadlineFontSize: CGFloat = 80
            public let quadKickerFontSize: CGFloat = 26
            public let quadHeadlineLineHeight: CGFloat = 88
            public let qTeaserTitleInlineSpace: CGFloat = 24
            public let teaserBadgesMarginSpace: CGFloat = 8
            public let teaserBadgesHeightSizeLg: CGFloat = 40
            public let teaserTitleBottomStackSpace: CGFloat = 16
            public let teaserBadgesHeightSizeSm: CGFloat = 32
            public let bildPlayTeaserWidthSize: CGFloat = 193
            public let teaserLayoutGridSpace: CGFloat = 16
            public let superAteaserTitleInlineSpace: CGFloat = 24
            public let bTeaserTitleInlineSpace: CGFloat = 16
        }
    }

    // MARK: - Typography

    /// Typography tokens protocol
    public protocol SportbildTeaserTypographyTokens: Sendable {
        var aTeaserATeaserKicker: TextStyle { get }
        var aTeaserATeaserHeadline: TextStyle { get }
        var mQteaserMQteaserKicker: TextStyle { get }
        var mQteaserMQteaserHeadline: TextStyle { get }
        var qTeaserQTeaserHeadline: TextStyle { get }
        var stdTeaserStdTeaserHeadline: TextStyle { get }
    }

    /// Typography accessor
    public enum Typography {
        /// Returns typography tokens for the specified size class
        public static func current(for sizeClass: SizeClass) -> any SportbildTeaserTypographyTokens {
            sizeClass == .compact ? Compact.shared : Regular.shared
        }

        public static var compact: Compact { Compact.shared }
        public static var regular: Regular { Regular.shared }

        public struct Compact: SportbildTeaserTypographyTokens {
            public static let shared = Compact()
            private init() {}
            public let aTeaserATeaserKicker: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 16, lineHeight: 16, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let aTeaserATeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 30, lineHeight: 30, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserKicker: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 14, lineHeight: 15.4, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 21, lineHeight: 23.1, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let qTeaserQTeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 42, lineHeight: 42, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let stdTeaserStdTeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 21, lineHeight: 23.1, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }

        public struct Regular: SportbildTeaserTypographyTokens {
            public static let shared = Regular()
            private init() {}
            public let aTeaserATeaserKicker: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 26, lineHeight: 26, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let aTeaserATeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 50, lineHeight: 57.6, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserKicker: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 18, lineHeight: 19.8, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let mQteaserMQteaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 34, lineHeight: 39.1, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let qTeaserQTeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .black, fontSize: 80, lineHeight: 88, letterSpacing: 0, textCase: .original, textDecoration: .none )
            public let stdTeaserStdTeaserHeadline: TextStyle = TextStyle( fontFamily: "AntennaExtraCond", fontWeight: .bold, fontSize: 26, lineHeight: 29.9, letterSpacing: 0, textCase: .original, textDecoration: .none )
        }
    }

    // MARK: - Effects

    /// Effects tokens protocol
    public protocol SportbildTeaserEffectsTokens: Sendable {
        var teaserHeadlinesShadow: ShadowStyle { get }
    }

    /// Effects accessor
    public enum Effects {
        /// Returns effects tokens for the specified theme mode
        public static func current(isDark: Bool) -> any SportbildTeaserEffectsTokens {
            isDark ? Dark.shared : Light.shared
        }

        public static var light: Light { Light.shared }
        public static var dark: Dark { Dark.shared }

        public struct Light: SportbildTeaserEffectsTokens {
            public static let shared = Light()
            private init() {}
            public let teaserHeadlinesShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.60), offsetX: 0, offsetY: 2, radius: 8, spread: 0) ])
        }

        public struct Dark: SportbildTeaserEffectsTokens {
            public static let shared = Dark()
            private init() {}
            public let teaserHeadlinesShadow: ShadowStyle = ShadowStyle(shadows: [ DropShadow(color: Color(hex: 0x000000, alpha: 0.60), offsetX: 0, offsetY: 2, radius: 8, spread: 0) ])
        }
    }
}
